### ISSUE TITLE
Update Code of Conduct from nf-core template

### ISSUE THREAD

**Issue by heuermh** [nf-core/viralrecon#10]
Depends on https://github.com/nf-core/tools/issues/598

**Comment by drpatelh** [comment]
Will close this @heuermh in favour of it being added in https://github.com/nf-core/tools/issues/598 and then propagating itself through to this pipeline via the automated sync when tools is next released 👍 Hope thats ok.

**Comment by heuermh** [comment]
Yes, that sounds fine, thanks!
