### ISSUE TITLE
Addition of "save_mapped_reads_only" parameter

### ISSUE THREAD

**Issue by ameynert** [nf-core/viralrecon#107]
For metagenomic samples, exclude unmapped reads from final output BAM file.

**Comment by drpatelh** [comment]
Added here https://github.com/nf-core/viralrecon/pull/106/commits/8aba82fe1cbb885f3df7bb1162f52d63752830cc

Is this ok @ameynert?

**Comment by ameynert** [comment]
Looks good to me, thanks!
