### ISSUE TITLE
Per-amplicon coverage plot

### ISSUE THREAD

**Issue by drpatelh** [nf-core/viralrecon#112]
It would be nice to be able to generate per-amplicon coverage plots when using `--protocol amplicon` in order to assess dropouts/primers that suffer from poor coverage e.g.

![image (1)](https://user-images.githubusercontent.com/23529759/83666227-831b5100-a5c4-11ea-9afb-4219e526aabf.png)

![image (2)](https://user-images.githubusercontent.com/23529759/83666427-da212600-a5c4-11ea-88d7-990335004e0a.png)

The read count per primer sequence is already printed to the log files created by `ivar trim`:

```
Found 196 primers in BED file

Number of references in file: 1
NC_045512.2
Using Region: NC_045512.2

Found 2372934 mapped reads
Found 0 unmapped reads
Sorted By Coordinate
-------
Processed 10% reads ...
Processed 20% reads ...
Processed 30% reads ...
Processed 40% reads ...
Processed 50% reads ...
Processed 60% reads ...
Processed 70% reads ...
Processed 80% reads ...
Processed 90% reads ...
Processed 100% reads ...

-------
Results:
Primer Name     Read Count
nCoV-2019_1_LEFT        11671
nCoV-2019_1_RIGHT       11316
nCoV-2019_2_LEFT        5256
nCoV-2019_2_RIGHT       4912
nCoV-2019_3_LEFT        36850
nCoV-2019_3_RIGHT       36308
nCoV-2019_4_LEFT        33741
....
....
```

 @gkarthik would it be sensible to use this information to create these plots? If not, any help, tips or even scripts would be really useful. Thank you!

**Comment by gkarthik** [comment]
The log only reports reads from which primers were trimmed off but with NextEra to get the true counts you will have to check reads that start and end within the left and right primers of an amplicon. Will require some tweaking of code to log that as well but unfortunately I'm rather occupied with other SARS-CoV-2 things at the moment.

**Comment by drpatelh** [comment]
No worries! Thanks alot for the rapid response as always @gkarthik 😎 Agreed, crazy times! Are you aware of any scripts I can use to do such a thing or get an idea as to which tools to use to generate the plots? I have an idea but would rather avoid re-inventing the wheel.

**Comment by gkarthik** [comment]
I think samtools has been writing code to do the same primer trimming and get stats for each amplicon - https://github.com/samtools/samtools/pull/1261. Not quite sure of other tools though!

**Comment by svarona** [comment]
We made something similar, not as cool but maybe you can find it helpful. We have the scripts here https://github.com/BU-ISCIII/SARS-Cov2_analysis/tree/master/Illumina-amplicons/13-amplicon_plots
We perform first bedtools coverage to obtain the depth and coverage of the amplicons, for this we use a modified .bed with the start and end position of the amplicons for both forward and reverse primers. In the case that for the same amplicon there were both normal and altered positions, we took the longest one. To create this file we just took the original .bed file and parsed it, so for the same amplicon instead of having one line for the RIGHT and another line for the LEFT we have just one amplicon per line. Then we use R to create the plots.

**Comment by drpatelh** [comment]
Initial implementation in https://github.com/nf-core/viralrecon/pull/119

So I wrote a [custom script](https://github.com/nf-core/viralrecon/pull/119/files#diff-09ad54181cc3e026d52aa86a1c376e2d) to collapse the amplicon bed files based on some sort of standard naming convention for left and right primers in the BED file. Works with all of the ARTIC BED files.

Was very easy to use `mosdepth` to get genome-wide coverage in 200bp windows as well as per-amplicon coverage and then to plot in `R`. Some examples in [this comment](https://github.com/nf-core/viralrecon/pull/119#issuecomment-645263567).
