### ISSUE TITLE
Speed-up SRA/ENA downloads with Aspera ascp 

### ISSUE THREAD

**Issue by rsuchecki** [nf-core/viralrecon#115]
Current handling of SRA/ENA downloads is already robust and multi-tiered. 
It could be further improved if primary mode of download used https://en.wikipedia.org/wiki/Fast_and_Secure_Protocol.

Since `bin/fetch_sra_runinfo.py` already returns available fasp urls the first download attempt could be ascp, with FTP then `parallel-fastq-dump` as fallback. 

Although Aspera CLI is proprietary software, it appears that the client comes with a free license.

According to [official documentation for an earlier version](http://download.asperasoft.com/download/docs/cli/3.7.2/user_linux/pdf2/Aspera_CLI_Guide_3.7.2_Linux.pdf):

> **Required Aspera Licenses**
> • The Aspera CLI requires a Connect-enabled license on the transfer server. For detailed information on your transfer server's license file, see the Aspera Connect Server Admin Guide .
> • The Aspera CLI package includes a free client license. It or another valid aspera-license file must be present in the Aspera CLI installation directory

Full license text can be found in the [official container](https://hub.docker.com/r/ibmcom/aspera-cli/) under [`/home/aspera/.aspera/cli/docs/LI_LA_non_ibm_license_en`](https://github.com/nf-core/viralrecon/files/4739348/LI_LA_non_ibm_license_en.txt)

According to more recent documents, license information is obtained as follows:

```
docker run --rm  -it ibmcom/aspera-cli ascp  --version 
IBM Aspera CLI version 3.9.1.1401.be67d47
ascp version 3.9.1.167862
Operating System: Linux
FIPS 140-2-validated crypto ready to configure
AES-NI Supported
License max rate=(unlimited), account no.=1, license no.=1
```

Related notes:
https://github.com/unlhcc/hcc-conda-recipes/issues/8

Edit: potential reason for **not** going with aspera https://github.com/ncbi/sra-tools/issues/304#issuecomment-639978013

**Comment by drpatelh** [comment]
> Edit: potential reason for **not** going with aspera [ncbi/sra-tools#304 (comment)](https://github.com/ncbi/sra-tools/issues/304#issuecomment-639978013)

Thanks @rsuchecki. So it's probably not worth going through the effort of implementing this afterall then. That settles it.

**Comment by drpatelh** [comment]
> > Edit: potential reason for **not** going with aspera [ncbi/sra-tools#304 (comment)](https://github.com/ncbi/sra-tools/issues/304#issuecomment-639978013)
> 
> Thanks @rsuchecki. So it's probably not worth going through the effort of implementing this afterall then. That settles it.

**Comment by tamuanand** [comment]
@drpatelh @pditommaso

This reply of mine is based of this comment from @drpatelh  - https://github.com/nextflow-io/nextflow/pull/1611#issuecomment-640460251

I wanted to share what I know:
- I have been working with EBI folks on Annotare/ArrayExpress. While it might be true that NCBI is moving SRA to the cloud, I think EBI/ENA still has data on-prem for SRA
- according to the ArrayExpress EBI scientist who was helping me "aspera cli is free to use"

Vested interest :) - been requesting @pditommaso to have a `fromSRA` variant in nextflow that piggyback on asperacli with EBI/ENA and/or use the ncbi sra data in AWS/GCP
