### ISSUE TITLE
Pipeline output documentation

### ISSUE THREAD

**Issue by drpatelh** [nf-core/viralrecon#12]
We will need to properly document/explain all of the outputs generated by the pipeline along with some nice plots and figures:
https://github.com/nf-core/atacseq/blob/dev/docs/output.md

**Comment by drpatelh** [comment]
This was initially added here https://github.com/nf-core/viralrecon/pull/48

**Comment by ktrns** [comment]
Hi @drpatelh 

I have made little changes here and there and will create a PR soon. 

**Questions that came up in `usage.md`:** 
Would it be possible to add a sentence to `--amplicon_bed` and `--amplicon_fasta` to say what it is needed for? Why is a bed file needed if we map the reads any way? Why is a fasta file needed if we assemble anyways?

Why are `VarScan2` and `iVar` used for variant calling of reads against the reference genome, and `Minimap2`, `seqwish`, `vg` for variant calling of de-novo assemblies against the reference genome? Are the latter ones better suited for genome vs. genome? And why is specifically `vg` failing? Does `--run_vg` run specifically `vg`, or `Minimap2` and `seqwish` as well? (I obviously don't know these tools yet and don't know about the concept of a variant graph yet)

Why is especially minia failing and hence not in the defaults for `--assemblers`?

**Questions that came up in `output.md`:** 
Why are you using different trimming tools? `fastp` for general adapter trimming, `iVar trim` before variant calling, `Cutadapt` before de-novo assembly. 

Best
Katrin

**Comment by drpatelh** [comment]
Docs are looking nice now as of https://github.com/nf-core/viralrecon/pull/103
