### ISSUE TITLE
IGV batch screenshots

### ISSUE THREAD

**Issue by drpatelh** [nf-core/viralrecon#121]
Be good if we can output IGV screenshots for variants without having to load the BAM files. It can take ages to load these relative to the viral genome due to the high depth. I havent tried it before but would be worth looking into. See [here](http://software.broadinstitute.org/software/igv/automation) for some docs.

**Comment by heuermh** [comment]
Where is this happening in the workflow?  I wonder if https://github.com/bigdatagenomics/mango might be able to help.

**Comment by drpatelh** [comment]
An alternative solution to this would be [asciigenome](https://asciigenome.readthedocs.io/en/latest/) too. Maybe a command like the below would do the trick:

- Get a list of variants in BED format from the VCF file and pad by 50bp either side to zoom out a little

```console
zcat TOL743A312592_S192_L001.vcf.gz | grep -v '#' | awk -v FS='\t' -v OFS='\t' '{print $1, ($2-50), ($2+50+1)}' > batch.txt
```

- Run  ASCIIGenome

```console
ASCIIGenome -ni -x "trackHeight 25 && readsAsPairs -on && save TOL743A312592_S192_L001.%r.pdf" --batchFile batch.txt --fasta MN908947.3.fa TOL743A312592_S192_L001.ivar_trim.sorted.bam TOL743A312592_S192_L001.vcf.gz > /dev/null
```

**Comment by drpatelh** [comment]
Added ASCIIGenome for its awesome batch processing more here https://github.com/nf-core/viralrecon/pull/186
