### ISSUE TITLE
Modules required for DSL 2 implementation of pipeline

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/viralrecon#149]
- [x] fastp
- [x] bowtie2 index
- [x] bowtie2 align
- [x] snpeff 
- [x] snpsift extractFields
- [x] samtools view
- [x] samtools mpileup
- [x] samtools faidx
- [x] ivar trim
- [x] picard collectwgsmetrics
- [x] mosdepth
- [x] varscan mpileup2cns
- [x] bcftools stats
- [x] bcftools filter
- [x] tabix
- [x] bedtools genomecov
- [x] bedtools maskfasta
- [x] quast
- [x] ivar variants
- [x] ivar consensus 
- [x] bcftools mpileup
- [x] bcftools isec
- [x] bcftools concat
- [x] [blast?] makeblastdb
- [x] kraken2-build
- [x] cutadapt
- [x] spades
- [x] blast blastn
- [x] abacas
- [x] plasmidID
- [x] minimap2 (assigned @heuermh [#149](https://github.com/nf-core/modules/pull/149))
- [x] seqwish (assigned @heuermh [#221](https://github.com/nf-core/modules/pull/221))
- [x] vg view (deprecated)
- [x] vg convert (deprecated)
- [x] vg snarls (deprecated)
- [x] vg deconstruct (deprecated)
- [x] minia
- [x] bandage image
- [x] unicycler 
- [x] pangolin
- [ ]  [nextclade](https://github.com/nextstrain/nextclade)

**Comment by drpatelh** [comment]
Goodness me, that's a bigger list than I was expecting!! 😅

**Comment by heuermh** [comment]
Once the pattern is in place, I should be able to handle the seqwish/vg ones

**Comment by cjfields** [comment]
Following on what @heuermh said: is there a general 'nf-core'-y template (a standard way) that DSL2 modules are being set up?  This would be of general use to other Nextflow and nf-core projects

**Comment by heuermh** [comment]
@cjfields Yes, there is plenty of discussion in the modules channel on Slack (https://nfcore.slack.com/archives/CJRH30T6V) and I believe the https://github.com/nf-core/rnaseq workflow is leading the way

**Comment by drpatelh** [comment]
What @heuermh said and https://github.com/nf-core/modules for good measure.

**Comment by drpatelh** [comment]
### Modules ready to push to nf-core/modules

- [ ] [bandage.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bandage.nf)
- [ ] [bcftools_bgzip.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bcftools_bgzip.nf)
- [ ] [bcftools_consensus.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bcftools_consensus.nf)
- [ ] [bcftools_filter.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bcftools_filter.nf)
- [ ] [bcftools_isec.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bcftools_isec.nf)
- [ ] [bcftools_stats.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bcftools_stats.nf)
- [ ] [bcftools_tabix.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bcftools_tabix.nf)
- [ ] [bedtools_maskfasta.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bedtools_maskfasta.nf)
- [ ] [bedtools_merge.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bedtools_merge.nf)
- [ ] [blast_blastn.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/blast_blastn.nf)
- [ ] [blast_makeblastdb.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/blast_makeblastdb.nf)
- [ ] [bowtie2_align.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bowtie2_align.nf)
- [ ] [bowtie2_build.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bowtie2_build.nf)
- [ ] [cat_fastq.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/cat_fastq.nf)
- [ ] [fastp.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/fastp.nf)
- [ ] [gunzip.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/gunzip.nf)
- [ ] [ivar_consensus.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/ivar_consensus.nf)
- [ ] [ivar_trim.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/ivar_trim.nf)
- [ ] [ivar_variants.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/ivar_variants.nf)
- [ ] [minia.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/minia.nf)
- [ ] [mosdepth.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/mosdepth.nf)
- [ ] [picard_collectwgsmetrics.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/picard_collectwgsmetrics.nf)
- [ ] [plasmidid.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/plasmidid.nf)
- [ ] [quast.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/quast.nf)
- [ ] [samtools_mpileup.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/samtools_mpileup.nf)
- [ ] [samtools_view.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/samtools_view.nf)
- [ ] [unicycler.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/unicycler.nf)
- [ ] [untar.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/untar.nf)
- [ ] [varscan_mpileup2cns.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/varscan_mpileup2cns.nf)

### Modules with container issues
- [ ] [spades.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/spades.nf) - Unable to add to Conda due too C lib issues. Need to push a custom container to nf-core. Currently using one from Dockerhub
- [ ] [abacas.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/abacas.nf) - Biocontainer doesn't exist. Package does exist on Conda but not on Bioconda. Needs to be added there first

### Modules with customisation that we may not be able to push to nf-core/modules
- [ ] [snpsift_extractfields.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/snpsift_extractfields.nf) - Using custom options, attempt to make the module more generic
- [ ] [cutadapt.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/cutadapt.nf) - Have to stage a separate adapters.fa for primer trimming
- [ ] [bcftools_mpileup.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bcftools_mpileup.nf) - Has pipes to other tools
- [ ] [bedtools_genomecov.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bedtools_genomecov.nf) - Only supports BAM input currently
- [ ] [kraken2_build.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/kraken2_build.nf) - Unfinished - requires more thought!
- [ ] [kraken2_run.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/kraken2_run.nf) - Outputs may be too custom?
- [ ] [snpeff_ann.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/snpeff_ann.nf) - Requires custom database and staging options
- [ ] [snpeff_build.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/snpeff_build.nf) - Only supports custom database build for the pipeline

**Comment by andersgs** [comment]
@drpatelh you can assign ivar to me, I have then written and just adding some tests.

**Comment by andersgs** [comment]
@drpatelh can you send me the issue you are having with spades on bioconda? i can work with it.

**Comment by JoseEspinosa** [comment]
Hi @drpatelh I have a couple of questions regarding the implementation of the `bcftools_isec` module, first I am not sure whether it will be used since it is now [commented](https://github.com/drpatelh/nf-core-viralrecon/blob/49958949843c36114c4b72832a7cafb0cd6afbf6/workflows/illumina.nf#L475-L487).
Then, I saw that each `vcf` file (and corresponding `tbi` index) is provided as a separate channel in the [declaration](https://github.com/drpatelh/nf-core-viralrecon/blob/c82eb410b0d9dabbce87444f044e30becbc35efe/modules/local/bcftools_isec.nf#L21) of the input channel. Wouldn't it be more convenient to declare a single path and `collect` all the files before inputting them in the module. This way the declaration of the module input would be more generic.

**Comment by drpatelh** [comment]
Amazing! Thanks @andersgs 😎 I will wait for you to push the modules here before I install and use them in viralrecon. It would be great if `ivar variants` and `ivar consensus` are able to support both BAM and `mpileup` input. We have had questions posed about variants being called where we have had to ask users to go back to the `mpileup` files. That's one of the reasons I have an explicit step for `mpileup` generation, and the other one is that the `mpileup` file can be generated with exactly the same parameters and passed to VarScan2 too. We are using BAM input and pipes for `BCFTools` via `bcftools mpileup`. Let's discuss on your PRs 👍🏽

**Comment by drpatelh** [comment]
@JoseEspinosa yes, my bad, I still need to do a little work on that process but I have moved it to the "not fit for nf-core/modules" section at the bottom. It is commented out in the main workflow because I added some fresh sub-workflows for each variant caller at the end of last week, and I need to sort out all of the channels to get it working again 🙂 

Currently, the reason why can't use a simple `collect` there is because I have used exactly the same naming convention for each of the callers for simplicity. This means if we stage them all together then Nextflow will barf. This is why they are being staged in their own directories at the moment. This one may have to stay as a local module but you could maybe add a generic one to nf-core/modules that just takes a list of `tuple val(meta), path(vcfs)`. It would be a good start anyway and we almost certainly expect these modules to be updated. Adding the tests and docs is always the bit that takes the longest 😅

**Comment by andersgs** [comment]
Rather than add samtools as a separate step (I am thinking of minimising having to spin up containers), would it better off to add `tee` to the step and capture the output --- perhaps optionally:

`samtools mpileup | tee pileup.txt | ivar consensus`

I agree that we should be moving the `bcftools mpileup` (since samtools mpileup is being deprecated) but the docs for ivar are clear on depending on `samtools mpileup`, I haven't chased up with the ivar team on this.

**Comment by drpatelh** [comment]
> Rather than add samtools as a separate step (I am thinking of minimising having to spin up containers), would it better off to add tee to the step and capture the output --- perhaps optionally:

Great idea! Sounds like a good compromise 👍🏽 I will just pass the same mpileup generating arguments I am using for VarScan here too.

**Comment by drpatelh** [comment]
I am assuming the Andersen lab have been ridiculously over-run. We added a MultiQC module for iVar last year and a script to convert the tabular output to VCF. Still waiting for the latter to be added officially too.

**Comment by heuermh** [comment]
@drpatelh [bandage.nf](https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/bandage.nf) looks reasonable to me, what do you need to push to nf-core/modules? I can pick that up if you'd like

**Comment by drpatelh** [comment]
That would be great @heuermh. I assigned it to you in the issue above 👍🏽 I haven't written a module for `minia` (or any of the other variant graph modules) yet but feel free to assign yourself / add any of the others above too 🙂 I have been quite pre-occupied with overhauling the CI tests we are using on nf-core/modules but hoping to come back to a sprint here soon.

**Comment by drpatelh** [comment]
Awesome work guys! Especially @JoseEspinosa 😎 Going to close this issue since we are pretty much done. Thank you!
