### ISSUE TITLE
Test Not Working On Cluster

### ISSUE THREAD

**Issue by rmoczalla** [nf-core/viralrecon#156]
The setup is a cluser of machines with docker and nextflow installed. Each machine runs a `nextflow node` process and a docker daemon.

I am trying to run your workflow on the cluster by executing the following command on one node.
`nextflow run nf-core/viralrecon -profile test,docker -process.executor ignite`

The cluster starts to process the test pipeline, but get stuck in the following error.
```Error executing process > 'BOWTIE2_INDEX (GCF_009858895.2_ASM985889v3_genomic.200409.fna)'

Caused by:
  java.nio.file.NoSuchFileException: /work/3f/4b5b5e80605434963098c246e097b7/.command.run

Command executed:

  bowtie2-build \
      --seed 1 \
      --threads 2 \
      GCF_009858895.2_ASM985889v3_genomic.200409.fna \
      GCF_009858895.2_ASM985889v3_genomic.200409
  mkdir Bowtie2Index && mv GCF_009858895.2_ASM985889v3_genomic.200409* Bowtie2Index

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /work/3f/4b5b5e80605434963098c246e097b7

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
-[nf-core/viralrecon] Pipeline completed with errors-
```
Each node of the cluster seems to do some work until the error appears.

**Comment by rmoczalla** [comment]
I was missing a shared /work directory among the cluster members.

**Comment by drpatelh** [comment]
Hi @rmoczalla ! I am glad you found a solution because Im not sure I would have been much help :)
