### ISSUE TITLE
test install not working, sra toolkit failure

### ISSUE THREAD

**Issue by jhill1440** [nf-core/viralrecon#167]
Hello,

I am just trying the test data set using this command

nextflow run nf-core/viralrecon -profile test,singularity

It starts running and downloads the container but then after a while throws this error:

Error executing process > 'get_software_versions'

Caused by:
  Process `get_software_versions` terminated with an error exit status (132)

Command executed:

  echo 1.1.0 > v_pipeline.txt
  echo 20.10.0 > v_nextflow.txt
  parallel-fastq-dump --version > v_parallel_fastq_dump.txt
  fastqc --version > v_fastqc.txt
  fastp --version 2> v_fastp.txt
  bowtie2 --version > v_bowtie2.txt
  samtools --version > v_samtools.txt
  bedtools --version > v_bedtools.txt
  mosdepth --version > v_mosdepth.txt
  picard CollectMultipleMetrics --version &> v_picard.txt || true
  ivar -v > v_ivar.txt
  echo $(varscan 2>&1) > v_varscan.txt
  bcftools -v > v_bcftools.txt
  snpEff -version > v_snpeff.txt
  echo $(SnpSift 2>&1) > v_snpsift.txt
  quast.py --version > v_quast.txt
  cutadapt --version > v_cutadapt.txt
  kraken2 --version > v_kraken2.txt
  spades.py --version > v_spades.txt
  unicycler --version > v_unicycler.txt
  minia --version > v_minia.txt
  blastn -version > v_blast.txt
abacas.pl -v &> v_abacas.txt || true
  plasmidID -v > v_plasmidid.txt  || true
  Bandage --version > v_bandage.txt
  minimap2 --version > v_minimap2.txt
  vg version > v_vg.txt
  echo $(R --version 2>&1) > v_R.txt
  multiqc --version > v_multiqc.txt
  scrape_software_versions.py &> software_versions_mqc.yaml

Command exit status:
  132

Command output:
  (empty)

Command error:
  This sra toolkit installation has not been configured.
  Before continuing, please run: vdb-config --interactive
  For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
  tput: No value for $TERM and no -T specified
  tput: No value for $TERM and no -T specified
  QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-joshua.hill'
  .command.sh: line 28:  1890 Illegal instruction     (core dumped) vg version > v_vg.txt

Work dir:
  /home/joshua.hill/work/56/51b8e6286b45f1e3e33b255e3de9ac

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command li
ne

Not sure why this is happening but is this in the singularity container?

This is a generic centos7 machine that it is running on.  I have used singularity successfully in the past so I think that installation is correct.  I just installed nextflow so maybe it that is not configured correctly.

[joshua.hill@buddy work]$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
[joshua.hill@buddy work]$ nextflow -v
nextflow version 20.10.0.5430
[joshua.hill@buddy work]$ singularity version
3.7.1-1.el7

Thanks for any help.

**Comment by drpatelh** [comment]
Hi @jhill1440 ! Hope you are well. Apologies for the late response. Just catching up with all of these issues before the next release. Did you manage to fix this? We have made quite a few updates in the pipeline for the next release which you can test with:

```console
nextflow pull nf-core/viralrecon
nextflow run nf-core/viralrecon ......... -r dev
```

Hopefully, that will fix this issue so will close for now but if you have any problems getting the pipeline running it will be much easier to ping us on [Slack](https://nf-co.re/join) in the #viralrecon channel.
