### ISSUE TITLE
ivar trimming of Swift libraries new offset feature

### ISSUE THREAD

**Issue by rrdavis77** [nf-core/viralrecon#170]
Came across these improvements for ivar in the IDseq github:

https://github.com/chanzuckerberg/idseq-workflows/commit/d922823410d03dbae30f6476b11b77dbfacacd41

https://github.com/andersen-lab/ivar/pull/88

When processing swift libraries polymerases can add additional bases causing issues with trimming.  I guess this happens for swift libraries only?

**Comment by drpatelh** [comment]
Added a new parameter called `--ivar_trim_offset` to be able to customise this behaviour. As suggested in the issues linked to above if you are using the SWIFT/SNAP protocol then you will need to set `--ivar_trim_offset 5` when running the pipeline. 

The pipeline will also now attempt to auto-detect whether you are using the SWIFT/SNAP protocol based on the assumption that you have used `covid19genome` in the name field of the primer BED file. This name is used in the original SWIFT master file containing the primer co-ordinates.

![image](https://user-images.githubusercontent.com/23529759/116281311-7de96680-a781-11eb-9dde-6c2222bff0c7.png)
