### ISSUE TITLE
MultiQC report does not include all the metrics

### ISSUE THREAD

**Issue by rrdavis77** [nf-core/viralrecon#175]
When running the dev nf-core/viralrecon v1.2.0dev (224865c), I noticed the multiQC report does not have information for Kraken2 % non-host reads even though the kraken2 reports are generated correctly.  There are NAs instead of actual percentages.  Also the coverage information is not displayed in the variant calling metrics section.
Thanks

Ryan

**Comment by rrdavis77** [comment]
![coverage_empty](https://user-images.githubusercontent.com/7916230/116288305-3db8c280-a746-11eb-9481-8f6c1735d26b.png)
![viralrecon_empty_kraken2](https://user-images.githubusercontent.com/7916230/116288315-3ee9ef80-a746-11eb-84de-ce8ddb510e96.png)
above are screenshots of the empty kraken2 and coverage info in the multiQC report.
I used the following command:
nextflow run nf-core/viralrecon --input /home/ryan/SWIFT_ENV_Nextseq/samplelist.csv --platform illumina --genome 'NC_045512.2' --protocol amplicon --primer_bed /home/ryan/SWIFT_test/NC_045512.2.v2.primers.bed --primer_fasta /home/ryan/SWIFT_test/NC_045512.2.v2.primers.fna --skip_assembly --skip_markduplicates -profile docker --max_memory '8.GB' --max_cpus 8 --primer_left_suffix F --primer_right_suffix R -r dev --kraken2_db /home/ryan/Downloads/kraken2_human.tar.gz

**Comment by drpatelh** [comment]
Ok. I figured out why this is failing. Its because the `multiqc_general_stats.yaml` isn't being generated since I updated to the v.1.10.1 of MultiQC:
https://github.com/nf-core/viralrecon/blob/58e391da941319466a61ed7a14fe1929b6ef05da/bin/multiqc_to_custom_csv.py#L127

Will do some more digging.

**Comment by drpatelh** [comment]
Ok. Will be fixed here https://github.com/nf-core/viralrecon/pull/179/commits/8f74780ab0a47523dba37c43f8c3cb0fec10c3d8
