### ISSUE TITLE
ivar outputs in vcf 

### ISSUE THREAD

**Issue by ibseq** [nf-core/viralrecon#177]
hi, 
reading from https://nf-co.re/viralrecon/1.0.0/output#ivar-variants-and-ivar-consensus
it seems you suggests ivar can output in vcf format top of tsv:  
variants/ivar/
<SAMPLE>.tsv: Low frequency variants in TSV format.
<SAMPLE>.vcf.gz: Low frequency variants VCF file.
<SAMPLE>.vcf.gz.tbi: Low frequency variants VCF index file.

I cannot read anywhere how to run ivar to call variants outputs in vcf. any suggestions?
thanks!
ibseq

**Comment by drpatelh** [comment]
Hi @ibseq iVar doesn't currently output variants in VCF format. We wrote a custom script for this pipeline that does the conversion from `tsv` -> `vcf`. The latest version of the script is [here](https://github.com/nf-core/viralrecon/blob/dev/bin/ivar_variants_to_vcf.py)

We have also shared this with the author of iVar just in case it comes in handy for them to add a native implementation :)
https://github.com/andersen-lab/ivar/issues/17

Hope that helps!

**Comment by ibseq** [comment]
Thanks!
