### ISSUE TITLE
Add mosdepth heatmap to MultiQC report

### ISSUE THREAD

**Issue by drpatelh** [nf-core/viralrecon#196]
Would be awesome if we can include the mosdepth amplicon coverage heatmap in the MultiQC report too. Just need to export the matrix from the [custom R script](https://github.com/nf-core/viralrecon/blob/master/bin/plot_mosdepth_regions.r) we are using by adding a line or two. Can then create custom content for MultiQC to chomp like we are doing in the rnaseq pipeline for the DESeq2 heatmap.

@ewels pointed to some colour codes to get the same palette as in the PDF heatmap:
"Here are the colour codes for the blue-yellow (viridis) colour scale: 
https://jarrettmeyer.com/2018/08/07/viridis-color-palette

Get a list of 12 or so of them and set them as the colour_stops config option (or something like that it was, maybe check the docs)"

**Comment by ewels** [comment]
https://multiqc.info/docs/#heatmaps - `colstops` 👍🏻

**Comment by drpatelh** [comment]
Added in https://github.com/nf-core/viralrecon/pull/202

## Nanopore test data:

### Original PDF
![image](https://user-images.githubusercontent.com/23529759/121596053-db3a2e00-ca36-11eb-9fed-634975ab8296.png)

### In MultiQC
![image](https://user-images.githubusercontent.com/23529759/121595701-71218900-ca36-11eb-937e-33f52508eede.png)

## Illumina data

**The scales look a little different but it's something I can live with**

### Original PDF
![image](https://user-images.githubusercontent.com/23529759/121596095-ea20e080-ca36-11eb-8cd8-5418c127dda3.png)

### In MultiQC:
![image](https://user-images.githubusercontent.com/23529759/121595939-bba30580-ca36-11eb-9981-2a73fb115954.png)
