### ISSUE TITLE
Output a .tsv comprising the Nextclade and Pangolin Results for all samples processed

### ISSUE THREAD

**Issue by Codes1985** [nf-core/viralrecon#197]
Hi There,

First of all, a big thank you to everyone developing and maintaining Viralrecon; it has become integral to our laboratory's SARS-CoV-2 response.

We were excited to see in the latest version that you have included both the Nextclade and Pangolin typing tools.  Would it be possible to generate a basic report (e.g., a .tsv file) comprising the sample name, clade and lineage calls?  I admit, I am being lazy here, but it might be a nice report to have generated when a user is processing a large number of samples.  For example:

Sample | Nextclade | Pangolin
---------|------------|--------
Frodo | 20A | B.1.617.2
Sam | 20A | B.1.617.2

Thanks again for all your hard work on Viralrecon, and for considering this request.

All the best,
Cody

**Comment by saramonzon** [comment]
Hi there!
Thanks for your suggestion, we're actually working on a variants-lineage report like this I think we can include both lineages no problem!
Will try to include it in the next release :)

**Comment by Codes1985** [comment]
Hi Sara,

That sounds most excellent.  Thanks for letting me know; we will look forward to it.

Take care,
Cody

**Comment by drpatelh** [comment]
![image](https://user-images.githubusercontent.com/23529759/121893439-de266e80-cd15-11eb-8b95-4cb3b55a8149.png)

Hi @Codes1985! We already had the Pangolin lineage info in the MultiQC report and summary metrics file generated by the pipeline in v2.0. I have now added the Nextclade clade info as you will see in the screenshot above. Not sure if you knew but the pipeline also saves a csv file with all of the summary metrics for all of the samples in the `results/multiqc/` folder.

I think that addresses the feature request in this issue so will close.

**Comment by Codes1985** [comment]
@drpatelh Thank you very much for this!
