### ISSUE TITLE
ASCIIGenome failing during analysis

### ISSUE THREAD

**Issue by charlesfoster** [nf-core/viralrecon#198]
## Check Documentation

I have checked the following places for your error:
- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core/viralrecon pipeline documentation](https://nf-co.re/nf-core/viralrecon/usage)

## Description of the bug

While running viralrecon using data from the SNAP/Swift protocol, the pipeline repeatedly crashed at the ASCIIGenome step:

![image](https://user-images.githubusercontent.com/11418858/121273453-a7aeb500-c90b-11eb-91e9-5ad2211df551.png)

If I skip the ASCIIGenome step (`--skip_asciigenome`), the pipeline finishes as expected. I was asked to create this issue by @drpatelh (https://nfcore.slack.com/archives/C0110R22NH3/p1623156803141900?thread_ts=1623119196.129800&cid=C0110R22NH3)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run nf-core/viralrecon --platform illumina --input samplesheet.csv  --genome 'NC_045512.2'  --protocol amplicon --primer_bed swift.bed --primer_left_suffix '_F' --primer_right_suffix '_R' --ivar_trim_offset 5 --skip_assembly -profile singularity --max_memory "50.0 GB"`
2. See error: 

```
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:VARIANTS_IVAR:ASCIIGENOME (sample1)'

Caused by:
  Process `NFCORE_VIRALRECON:ILLUMINA:VARIANTS_IVAR:ASCIIGENOME (sample1)` terminated with an error exit status (1)

Command executed:

  zcat sample1.vcf.gz \
      | grep -v '#' \
      | awk -v FS='	' -v OFS='	' '{print $1, ($2-50-1), ($2+50)}' \
      > variants.bed
  
  ASCIIGenome \
      -ni \
      -x "trackHeight 0 bam#1 && trackHeight 50 bam@2 && readsAsPairs -on && filterVariantReads && save sample1.%r.pdf" \
      --batchFile variants.bed \
      --fasta GCF_009858895.2_ASM985889v3_genomic.200409.fna \
      sample1.ivar_trim.sorted.bam \
      sample1.vcf.gz \
      swift.bed \
      GCF_009858895.2_ASM985889v3_genomic.200409.gff \
      > /dev/null
  
  echo $(ASCIIGenome -ni --version 2>&1) | sed -e "s/ASCIIGenome //g" > asciigenome.version.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Cannot read history file '/home/default/.asciigenome.yaml'
  
  Indexing 'GCF_009858895.2_ASM985889v3_genomic.200409.fna'.
  Initializing coordinates... Done from: sample1.ivar_trim.sorted.bam
  Cannot read history file '/home/default/.asciigenome.yaml'
  Invalid coordinates: -36 64
  Exception in thread "main" exceptions.InvalidGenomicCoordsException
  	at tracks.IntervalFeature.validateIntervalFeature(IntervalFeature.java:231)
  	at tracks.IntervalFeature.intervalFeatureFromBedLine(IntervalFeature.java:183)
  	at tracks.IntervalFeature.<init>(IntervalFeature.java:70)
  	at samTextViewer.Main.main(Main.java:150)
```
## Expected behaviour

ASCIIGenome to generate the correct output files, and for the pipeline to complete without error.

## Log files

Have you provided the following extra information/files:

- [X] The command used to run the pipeline
- [X] The `.nextflow.log` file
[nextflow.log](https://github.com/nf-core/viralrecon/files/6620311/nextflow.log)

## System

- Hardware: Desktop
- Executor: Just a simple `nextflow run` command
- OS: pop!_os
- Version  20.10

## Nextflow Installation

- Version: 21.04.1 build 5556

## Container engine

- Engine: Singularity
- version: Unsure
- Image tag: nf-core/viralrecon v2.0

## Additional context

What's the best way to privately share some reads that might allow the issue to be replicated?

**Comment by drpatelh** [comment]
This should be fixed in https://github.com/nf-core/viralrecon/pull/202 @charlesfoster. I submitted a PR to cfreate a multi-tool container that contains ASCIIGenome and BEDTools. The interval size adjustment will now be chucked through `bedtools slop` as an additional step to santise the intervals and to make sure they don't cross chromosomal boundaries. Be great if you can test this when that PR is merged.

```console
nextflow pull nf-core/viralrecon
nextflow run nf-core/viralrecon -r dev <YOUR_PARAMETERS>
```
