### ISSUE TITLE
config for 1200bp amplicon

### ISSUE THREAD

**Issue by KeyTals** [nf-core/viralrecon#214]
Hello,

Thank you for crating very useful pipeline. Is it possible to run this pipeline for ARTIC 1200bp amplicon kit?

https://www.protocols.io/view/sars-cov2-genome-sequencing-protocol-1200bp-amplic-btsrnnd6

Any suggestion will be useful.
Keyur

**Comment by drpatelh** [comment]
Hi @KeyTals ! Hope you are well. I have now added the required files and configuration to use the ARTIC V1200 primers with the pipeline [here](https://github.com/nf-core/configs/pull/257) and [here](https://github.com/nf-core/test-datasets/commit/b164fff5baf81455ebd8148d19c550ab5f002284).

You should be able to run the pipeline on e.g. Nanopore data by using `--primer_set_version 1200` . Be great if you can test and let me know everything looks as expected.

```bash
nextflow run nf-core/viralrecon \
    --input samplesheet.csv \
    --platform nanopore \
    --genome 'MN908947.3' \
    --primer_set_version 1200 \
    --fastq_dir fastq_pass/ \
    --fast5_dir fast5_pass/ \
    --sequencing_summary sequencing_summary.txt \
    -profile <docker/singularity/podman/conda/institute>
```

I will close this issue for now but please do feel free to come find us on the #viralrecon channel on [nf-core Slack](https://nf-co.re/join) if you have any more questions/issues. Hopefully, it will be quicker to get a response :)
