### ISSUE TITLE
Support for compressed FastQ files for Nanopore data

### ISSUE THREAD

**Issue by berguner** [nf-core/viralrecon#218]
Hello,

I realized that the pipeline only accepts uncompressed FastQ files as input for the Nanopore data processing. We always work with compressed FastQ files (.fastq.gz) in order to save space. It would be great if the pipeline can also take compressed files as input.

**Comment by drpatelh** [comment]
x-ref https://github.com/nf-core/viralrecon/issues/229#issuecomment-888521878

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/viralrecon/pull/250
