### ISSUE TITLE
Adding phylogeny tree for consensus fasta files

### ISSUE THREAD

**Issue by KeyTals** [nf-core/viralrecon#223]
Hello,

Thank you for creating very useful pipeline, this is just a suggestion but wouldn't it be useful to perform multiple sequence alignment on consensus fasta files as both illumina with ivar and Nanopore will generate census fasta and generate phylogeny tree to check for sample similarities? 

Keyur

**Comment by drpatelh** [comment]
Hi @KeyTals ! I think this sort of thing is out of the scope of this pipeline but I know @aunderwo has spent an amazing amount of time working on this sort of thing and may be able to point you to some external resources you can use to contextualise your samples?

**Comment by drpatelh** [comment]
As mentioned in the comment above online resources are available to perform this sort of analysis downstream e.g [Microreact](https://microreact.org/showcase), [Pangolin](https://cov-lineages.org/resources/pangolin.html) and [Nextclade](https://clades.nextstrain.org/).
