### ISSUE TITLE
Add BLASTDB_LMDB_MAP_SIZE environment variable to process BLAST_MAKEBLASTDB

### ISSUE THREAD

**Issue by ggrimes** [nf-core/viralrecon#225]
I am not sure if anyone had has this issue but I was getting the error
~~~
BLAST Database creation error: mdb_env_open: Cannot allocate memory
~~~
when I submitted the `NFCORE_VIRALRECON_ILLUMINA_PREPARE_GENOME_BLAST_MAKEBLASTDB` process to an SGE cluster.

To fix it I had to set the environment variable `BLASTDB_LMDB_MAP_SIZE=100000000` in a custom nextflow.config as described in the post here https://www.biostars.org/p/413294/

Could an environment variable `BLASTDB_LMDB_MAP_SIZE` be added as input to the process BLAST_MAKEBLASTDB ?

**Comment by ggrimes** [comment]
more information on the variable BLASTDB_LMDB_MAP_SIZE can be found here 

https://www.ncbi.nlm.nih.gov/books/NBK279684/

Makeblastdb application options. This application builds a BLAST database. An option of type “flag” takes no arguments, but if present the argument is true. Starting with the 2.10.0 release, makeblastdb produces version 5 databases by default, which uses LMDB. 

LMDB requires virtual memory (at least 600 GB, but 800 GB is recommended) to build an index. 

If makeblastdb cannot access enough virtual memory, it will produce a message containing the string “mdb_env_open”. 

Virtual memory is just that (virtual) and doesn’t depend on the hardware in your system. In general, we recommend that BLAST users simply set the virtual memory to unlimited. The other alternative is to use an environment variable (BLASTDB_LMDB_MAP_SIZE) to set the required virtual memory lower, but this runs the risk of LMDB not being able to complete indexing the database. For a smaller database (tens of millions of letters) it may be possible to use a value of 100 million.

**Comment by drpatelh** [comment]
Thanks for reporting @ggrimes ! I suspect this sort of setting would be better served in a user/institutional config because I and others using the pipeline haven't seen these issues before. You may be able to add it to the pipeline specific config you have for `eddie`?

**Comment by ggrimes** [comment]
Sure I will add it to our institutional config.
