### ISSUE TITLE
User defined JSON output for Nextclade

### ISSUE THREAD

**Issue by ampinzonv** [nf-core/viralrecon#226]
## Is your feature request related to a problem? Please describe

By default the pipeline outputs Nextclades's results only in CSV format. 
I find useful to have the result also in JSON format, it is more flexible for further analysis. To date there is no way to tell viralrecon to output any other format.

## Describe the solution you'd like

User defined option to tell viralrecon to output nextclade's results in json format.

## Describe alternatives you've considered

One possibility is via custom.config file. Since the CSV output is parsed downstream in the pipeline I think that outputting both formats is the best way to go. Not sure if it is possible to tell nextclade something like:
--output-json=output/nextclade.json \ 
--output-csv=output/nextclade.csv \

In one command line.

**Comment by drpatelh** [comment]
As added in https://github.com/nf-core/viralrecon/pull/230/commits/66ff1c2fef58859609f9ca1a96d2583b8b2a4e13 Nextclade will now output all files by default in the upcoming release. However, only the `csv` file will be published by default. You can output the `json` too using a `custom.config` like below:

```
params {
    modules {
        'nanopore_nextclade' {
            publish_files   = ['csv':'', 'json']
        }
    }
}
```

**Comment by ampinzonv** [comment]
Amazing, thank you very much.

**Comment by ampinzonv** [comment]
Dear @drpatelh just in case,
your suggestion of adding the following to custom.config in order to obtain the json file is not working:

params {
    modules {
        'nanopore_nextclade' {
            publish_files   = ['csv':'', 'json']
        }
    }
}
All it does is to create a directory named "json" full of CSV files.
The correct syntax is:

params {
    modules {
        'nanopore_nextclade' {
            publish_files   = ['json':'', '']
        }
    }
}

Regards,
