### ISSUE TITLE
2 errors when running pipeline test on minimal dataset

### ISSUE THREAD

**Issue by Nicolas-Fernandez** [nf-core/viralrecon#233]
Hi there! :)

## Check Documentation
I have checked the following places for my error:
https://nf-co.re/usage/troubleshooting
https://nf-co.re/viralrecon/usage

## Description of the bug
I follow README.md Quick Start steps 
Download and installation are ok, but cannot run test dataset or others command 

## Steps to reproduce

1. Command line:

nextflow run nf-core/viralrecon -profile test,singularity

2. See error:

N E X T F L O W  ~  version 19.07.0
Launching `nf-core/viralrecon` [serene_wiles] - revision: 2ebae61442 [master]
Script_cf2c5f68: 51: Not a valid include definition -- it must specify the module path as a string @ line 51, column 5.
       include { ILLUMINA } from './workflows/illumina'
       ^
│Script_cf2c5f68: 53: Not a valid include definition -- it must specify the module path as a string @ line 53, column 5.
       include { NANOPORE } from './workflows/nanopore'
       ^

2 errors

## Expected behaviour
Processed test dataset with succes to validate installation and start playing with my data :)

## Log files
The `.nextflow.log` file

## System
- Hardware: HPC
- Executor:  direct on node (can try slurm)
- OS: Linux
- Version: 3.10.0-693.11.6.el7.x86_64

## Nextflow Installation
- Version: 19.07.0

## Container engine
- Engine: Singularity
- version: 3.3.0-rc.1.73.gcbe1673

## Additional context
Thank you very much for your help ! :)

##### .nextflow.log #####
[nextflow.log](https://github.com/nf-core/viralrecon/files/6924762/nextflow.log)

**Comment by drpatelh** [comment]
Hi @Nicolas-Fernandez did you manage to solve this issue? It looks like you were using a very old version of NF (`19.07.0`). Be great if you can update to the latest [21.10.6](https://github.com/nextflow-io/nextflow/releases/tag/v21.10.6) and try again.

If you have any issues in the future it may be worth finding us in the #viralrecon channel on the [nf-core Slack workspace](https://nf-co.re/join) for real-time help.

**Comment by drpatelh** [comment]
Will close this now but feel free to re-open if the issue persists or you can come and find us on nf-core Slack as indicated in the issue above.
