### ISSUE TITLE
Nextclade version bump

### ISSUE THREAD

**Issue by marcmtk** [nf-core/viralrecon#235]
Hi there! I've only just discovered nf-core and this pipeline, i'm very impressed with how polished it is.

## Is your feature request related to a problem? Please describe
I noticed that nextclade is quite out of date, this leads to wrong clade calls. Currently the javascript implementation version 0.14.4 is used, the newest version is 1.3.0 (updated today). 

## Describe the solution you'd like

I'd like to see the version of nextclade increased. From what i can tell the newest version widely disseminated is 1.2.3
Conda: `bioconda::nextclade=1.2.3`
Singularity: `https://depot.galaxyproject.org/singularity/nextclade:1.2.3--h9ee0642_0`
Biocontainer: `quay.io/biocontainers/nextclade:1.2.3--h2eeb373_1`

## Describe alternatives you've considered

I've considered trying to bump the version myself, but i'm unsure how the code should be distributed between this repository and nf-core/modules. Also i'm very new to nextflow, so it's a bit overwhelming :smile:

## Additional context
Nextclade has received new required input parameters and removed at least one used output-parameter

Added required input for v. 1.2.3

- `--input-root-seq` should match the genome parameter
- `--input-tree` Path to Auspice JSON v2 file containing reference tree. 
- `--input-qc-config` Path to a JSON file containing configuration of Quality Control rules

Removed output option
- `--output-tsv-clades-only` which i think is used downstream in the multiQC 

Also it appears that the next version of nextclade (1.3.0) introduces a simpler input specification `--input-dataset=data/sars-cov-2`

**Comment by drpatelh** [comment]
Added in https://github.com/nf-core/viralrecon/pull/254 

See [website docs](https://nf-co.re/viralrecon/usage#updating-containers) for usage information.

To summarise:


A nextclade dataset feature was introduced in Nextclade CLI v1.3.0 that fetches input genome files such as reference sequences and trees from a central dataset repository. We have uploaded Nextclade dataset v2022-01-05 to nf-core/test-datasets, and for reproducibility, this will be used by default if you specifiy `--genome 'MN908947.3'` when running the pipeline.  However, there are a number of ways you can use a more recent version of the dataset:

- Supply your own by setting: `--nextclade_dataset <PATH_TO_DATASET>`
- Let the pipeline create and use the latest version by setting: `--nextclade_dataset false --nextclade_dataset_tag false`
- Let the pipeline create and use a specific, tagged version by setting: `--nextclade_dataset false --nextclade_dataset_tag <DATASET_TAG>`

If the `--save_reference` parameter is provided then the Nextclade dataset generated by the pipeline will also be saved in the `results/genome/` directory.
