### ISSUE TITLE
Shows "[nf-core/viralrecon] Pipeline completed successfully" after executing only 6 process

### ISSUE THREAD

**Issue by llk578496** [nf-core/viralrecon#236]
Hi all,

Thank you so much for developing this amazing pipeline!

I just tried to run the pipeline with the following command line and it seems to run at the first time, but it soon stops but with no error message. Also, it shows "[nf-core/viralrecon] Pipeline completed successfully-", but the downstream analysis discontinued. May I know if others also encountered this problem and how to solve this? 

I have checked fastq_pass/barcode33 to fastq_pass/barcode48 contains the fastq.gz files.

Samplesheet, log, command line, and terminal messages has been attached below.

Thank you very much for you help in advance. 

Eddie

Samplesheet:
[samplesheet.csv](https://github.com/nf-core/viralrecon/files/7083445/samplesheet.csv)

Log:
[.nextflow.log](https://github.com/nf-core/viralrecon/files/7083415/default.nextflow.log)

Command line:
"nextflow run nf-core/viralrecon --input samplesheet.csv --platform nanopore --genome 'MN908947.3' --primer_set_version 3 --fastq_dir fastq_pass/ --artic_minion_caller medaka --artic_minion_medaka_model r941_min_high_g360 -profile docker --max_memory 24.GB"

Log shows on the terminal:
"
------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/viralrecon v2.2
------------------------------------------------------
Core Nextflow options
  revision                 : master
  runName                  : drunk_nightingale
  containerEngine          : docker
  launchDir                : /mnt/data/Viralrecon/20210830_COVID_Batch91_guppyV5_partial
  workDir                  : /mnt/data/Viralrecon/20210830_COVID_Batch91_guppyV5_partial/work
  projectDir               : /home/gilmansiu3/.nextflow/assets/nf-core/viralrecon
  userName                 : gilmansiu3
  profile                  : docker
  configFiles              : /home/gilmansiu3/.nextflow/assets/nf-core/viralrecon/nextflow.config

Input/output options
  input                    : samplesheet.csv
  platform                 : nanopore

Reference genome options
  genome                   : MN908947.3
  fasta                    : https://github.com/artic-network/artic-ncov2019/raw/master/primer_schemes/nCoV-2019/V3/nCoV-2019.reference.fasta
  gff                      : https://github.com/nf-core/test-datasets/raw/viralrecon/genome/MN908947.3/GCA_009858895.3_ASM985889v3_genomic.200409.gff.gz
  primer_bed               : https://github.com/artic-network/artic-ncov2019/raw/master/primer_schemes/nCoV-2019/V3/nCoV-2019.primer.bed
  primer_set_version       : 3

Nanopore options
  fastq_dir                : fastq_pass/
  artic_minion_caller      : medaka
  artic_scheme             : nCoV-2019
  artic_minion_medaka_model: r941_min_high_g360

Max job request options
  max_memory               : 24.GB

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/viralrecon for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.3901628

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/viralrecon/blob/master/CITATIONS.md
------------------------------------------------------
executor >  local (6)
[28/41fec3] process > NFCORE_VIRALRECON:NANOPORE:PREPARE_GENOME:GUNZIP_GFF (GCA_009858895.3_ASM985889v3_genomic.200409.gff.gz) [100%] 1 of 1 ✔
[ba/b4665a] process > NFCORE_VIRALRECON:NANOPORE:PREPARE_GENOME:GET_CHROM_SIZES (nCoV-2019.reference.fasta)                    [100%] 1 of 1 ✔
[66/d83193] process > NFCORE_VIRALRECON:NANOPORE:PREPARE_GENOME:COLLAPSE_PRIMERS (nCoV-2019.primer.bed)                        [100%] 1 of 1 ✔
[df/d294e3] process > NFCORE_VIRALRECON:NANOPORE:PREPARE_GENOME:SNPEFF_BUILD (nCoV-2019.reference.fasta)                       [100%] 1 of 1 ✔
[b0/92b4ed] process > NFCORE_VIRALRECON:NANOPORE:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)                               [100%] 1 of 1 ✔
[-        ] process > NFCORE_VIRALRECON:NANOPORE:MULTIQC_CUSTOM_TSV_NO_SAMPLE_NAME                                             -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:MULTIQC_CUSTOM_TSV_NO_BARCODES                                                -
[a8/89c1d8] process > NFCORE_VIRALRECON:NANOPORE:MULTIQC_CUSTOM_TSV_BARCODE_COUNT                                              [100%] 1 of 1 ✔
[-        ] process > NFCORE_VIRALRECON:NANOPORE:ARTIC_GUPPYPLEX                                                               -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:MULTIQC_CUSTOM_TSV_GUPPYPLEX_COUNT                                            -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:NANOPLOT                                                                      -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:ARTIC_MINION                                                                  -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:FILTER_BAM_SAMTOOLS:SAMTOOLS_VIEW                                             -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:FILTER_BAM_SAMTOOLS:SAMTOOLS_INDEX                                            -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:FILTER_BAM_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_STATS                         -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:FILTER_BAM_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_FLAGSTAT                      -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:FILTER_BAM_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_IDXSTATS                      -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:BCFTOOLS_STATS                                                                -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:MOSDEPTH_GENOME                                                               -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:PLOT_MOSDEPTH_REGIONS_GENOME                                                  -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:MOSDEPTH_AMPLICON                                                             -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:PLOT_MOSDEPTH_REGIONS_AMPLICON                                                -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:PANGOLIN                                                                      -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:NEXTCLADE                                                                     -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:MULTIQC_CUSTOM_TSV_NEXTCLADE                                                  -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:QUAST                                                                         -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:SNPEFF_SNPSIFT:SNPEFF_ANN                                                     -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:SNPEFF_SNPSIFT:VCF_BGZIP_TABIX_STATS:TABIX_BGZIP                              -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:SNPEFF_SNPSIFT:VCF_BGZIP_TABIX_STATS:VCF_TABIX_STATS:TABIX_TABIX              -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:SNPEFF_SNPSIFT:VCF_BGZIP_TABIX_STATS:VCF_TABIX_STATS:BCFTOOLS_STATS           -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:SNPEFF_SNPSIFT:SNPSIFT_EXTRACTFIELDS                                          -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:ASCIIGENOME                                                                   -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:GET_SOFTWARE_VERSIONS                                                         -
[-        ] process > NFCORE_VIRALRECON:NANOPORE:MULTIQC                                                                       -
-[nf-core/viralrecon] Pipeline completed successfully-
"

**Comment by kibet-gilbert** [comment]
@llk578496 Yes this is a bug. 
Note that the pipeline only accepts decompressed fastq files. Please check if your fastq_pass/fastq* files are compressed i.e fastq.gz. This is what you get by default from the MinKnow or guppy barcoder. You can do `gunzip fastq_pass/*/fastq.gz` to decompress.
Good luck.

**Comment by llk578496** [comment]
@kibet-gilbert It works now! Thank you so much for your help!

**Comment by drpatelh** [comment]
Thanks for picking this up @kibet-gilbert ! Will close for now in favour of adding the functionality at some point!
