### ISSUE TITLE
AWS Access Key Id you provided does not exist in our records

### ISSUE THREAD

**Issue by anca-riza** [nf-core/viralrecon#242]
Hello!

Here running the typical command:
nextflow run nf-core/viralrecon --input samplesheet.csv --platform illumina --protocol amplicon --genome 'MN908947.3' --primer_set artic --primer_set_version 3 --skip_assembly -profile docker
produces:
The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: PJZXQ5FZAWTQH9GM; S3 Extended Request ID: TXcLDOz/N1yKf/fgFGradf2eg9cEo4asEzitppMlel7UsMg7b7fiv7pAnZqGdLRdJa7Kr+VpCVk=)

-- Check script '/home/genomica/.nextflow/assets/nf-core/viralrecon/./workflows/illumina.nf' at line: 25 or see '.nextflow.log' file for more details
nextflow.log attached
[nextflow.log](https://github.com/nf-core/viralrecon/files/7767431/nextflow.log)

Thank you for looking into this!

**Comment by drpatelh** [comment]
Hi @anca-riza ! Apologies for the late response! Hope you are well and Happy New Year!

Did you manage to solve this issue?

Looks like you have an existing AWS key in your home directory that may be causing the issue. You could try to rename that folder temporarily to see if it solves the issue:

```
Dec-22 23:26:33.854 [main] DEBUG nextflow.Global - Using AWS credential defined in `default` section in file: /home/genomica/.aws/credentials
```

May also be worth updating to the latest version of NF.

If you have any issues in the future it may be worth finding us in the #viralrecon channel on the [nf-core Slack workspace](https://nf-co.re/join) for real-time help.

**Comment by anca-riza** [comment]
Hi @drpatelh 

Thank you for your suggestion - it now works! All sorted out!

Bw,
Anca.

**Comment by drpatelh** [comment]
Awesome! Thanks for letting us know!

If you have any issues in the future it may be worth finding us in the #viralrecon channel on the [nf-core Slack workspace](https://nf-co.re/join) for real-time help.
