### ISSUE TITLE
Fix BCFtools consensus generation and masking

### ISSUE THREAD

**Issue by saramonzon** [nf-core/viralrecon#244]
## Check Documentation

I have checked the following places for your error:

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core/viralrecon pipeline documentation](https://nf-co.re/viralrecon/usage)

## Description of the bug
bcftools consensus fasta is renamed before consensus and masking command, so no variants are included in the consensus nor is masked. Reference genome is rendered.

We'll fix this.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/viralrecon/pull/255 https://github.com/nf-core/viralrecon/pull/256

Are we ok to close this @saramonzon @svarona ?

**Comment by saramonzon** [comment]
Yep! I think everything seems fine here!
