### ISSUE TITLE
Mpileup file as output

### ISSUE THREAD

**Issue by saramonzon** [nf-core/viralrecon#245]
## Is your feature request related to a problem? Please describe
Mpileup files can't be generated nor outputted by the pipeline, not even in the work dir. This could be problematic when debugging potential problems/issues with the results. 

## Describe the solution you'd like
We'd like a bcftools and samtools mpileup module to be independent from bcftools call and ivar variants modules so the user can choose to save the mpileup as output or not.
We prefer this option as bcftools and ivar could potentially use the same mpileup file so we can save time and resources.

## Describe alternatives you've considered
An alternative is not to create a new module, but the existing modules would not to pipe the mpileup file into bcftools call or ivar variants, so use could save the mpileup if desired.

**Comment by drpatelh** [comment]
Didn't we add a workaround for this :thinking_face: Lemme look

https://github.com/nf-core/viralrecon/blob/2ebae61442598302c64916bd5127cf23c8ab5611/modules/nf-core/modules/ivar/variants/main.nf#L34

Yep. But we should probably remove the params from the module and add it as an explicit input.

I suppose we could add a similar option to bcftools mpileup in a similar way too which would be useful as well:
https://github.com/nf-core/viralrecon/blob/2ebae61442598302c64916bd5127cf23c8ab5611/modules/nf-core/modules/bcftools/mpileup/main.nf#L39

**Comment by saramonzon** [comment]
This is already fixed here #256 right?

**Comment by drpatelh** [comment]
Yup 🚀
