### ISSUE TITLE
Option to generate consensus with BCFTools / BEDTools using iVar variants

### ISSUE THREAD

**Issue by saramonzon** [nf-core/viralrecon#246]
## Is your feature request related to a problem? Please describe
`ivar consensus` command has some issues already reported in their github: https://github.com/andersen-lab/ivar/issues/103 , https://github.com/andersen-lab/ivar/issues/97, https://github.com/andersen-lab/ivar/issues/85

## Describe the solution you'd like
We want an alternative method for generating the consensus using ivar variants and bcftools consensus. We'll select variants with AF > threshold and include them in the consensus, and we'll mask the consensus fasta as for bcftools caller.

**Comment by drpatelh** [comment]
Follow up fixes in https://github.com/nf-core/viralrecon/pull/264 https://github.com/nf-core/viralrecon/pull/265
