### ISSUE TITLE
repurposing viralrecon workflow for other viruses?

### ISSUE THREAD

**Issue by Krysasp** [nf-core/viralrecon#249]
Hi there! 

Thank you so much for the efforts in developing and contributing to this this excellent pipeline!

Is there guide for showing us how to experiment with other viruses by re-configuring workflow input settings especially genome reference and primers (how about degenerate primers?), via an offline pipeline will be greatly useful. ...

**Comment by drpatelh** [comment]
Hi @Krysasp ! Thanks for finding us!

The pipeline was intentionally written to be as generic as possible and I would hope that it can run on other viruses by just changing the appropriate parameters specific to your viral genome (e.g. `--fasta` and `--gff`) and any other pipeline specific parameters. Have you tried this?

I will cc @saramonzon @svarona here who I believe have used the pipeline for other viruses. Might be good to add a section to the docs for exactly which parameters we need to change in any case. Do you guys have an example command from another virus we could share with @Krysasp ?

**Comment by svarona** [comment]
We have a command for DSL1 to run with different virus, I'll paste it you here, but mainly is `--fasta` and `--gff` what you need to change. This is an example of mumps virus isolated from human genome:
`nextflow run main.nf -bg --input samplesheet.csv --kraken2_db human.tar.gz ---fasta AF280799.fasta --gff AF280799.gff
`

**Comment by drpatelh** [comment]
Thanks @svarona ! As I suspected then and we can maybe point to this issue if requiored. Ok, I will close this issue for now but if you have any more generic questions please come and find us in the #viralrecon channel on the [nf-core Slack workspace](https://nf-co.re/join).
