### ISSUE TITLE
Misuse of rstrip in make_variants_long_table.py script

### ISSUE THREAD

**Issue by fmaguire** [nf-core/viralrecon#277]
Hi folks.

There is a problem with the use of rstrip to remove file suffixes at https://github.com/nf-core/viralrecon/blob/master/bin/make_variants_long_table.py#L47 that can cause issues (and a workflow failure) for some sample names.

`rstrip` doesn't remove a specified substring from the end of string.
It actually removes any characters (and any number of them) regardless of order in the substring from the end of string.
`rstrip` only stops when it encounters a character in the string not in the specified substring.
e.g.,
```
"abaaacccca....ccaac".rstrip("ac.")
>>> "ab"
```
This means sample names containing characters in the suffix being removed get mangled:
```
filename='XXXX_P0_meta.oilcans.saponin.pangolin.csv'
suffix=".pangolin.csv"
print(filename.rstrip(suffix))
>>>XXXX_P0_met
```

Replacing rstrip with `removesuffix` should fix this in python >=3.9 (alternatively replace should be fine although a simple regex would be better!).

**Comment by drpatelh** [comment]
Hi @fmaguire ! Thanks for reporting! Created a patch release for v2.3.1 that I will get out today. A single word change turned into a bit of a 🐰 🕳️ and I have updated a bunch of other stuff too.
