### ISSUE TITLE
--primer_set_version only accepts Integers (incompatible with "4.1" Artic primers set)

### ISSUE THREAD

**Issue by tetedange13** [nf-core/viralrecon#288]
### Description of the bug

Hello,
<br>

First thanks for developping viralrecon, it is a wonderful tool !

Wanting to run your pipeline on Illumina data produced using "V4.1" Artic primer set and using [corresponding nf-core pre-defined primers set](https://github.com/nf-core/configs/blob/ff5750936db948e36d4a10fce8027b88de172823/conf/pipeline/viralrecon/genomes.config#L54-L59), I got bellow error as if `--primer_set_version` parameter could only accept integers
<br>

Thanks for your help !
Kind regard,
Felix.

### Command used and terminal output

```console
nextflow run nf-core-viralrecon-2.4/workflow \
        --genome 'MN908947.3' --platform illumina --protocol amplicon \
        --input SampleTable.csv --primer_set artic --primer_set_version 4.1 --outdir outdir \
        --kraken2_db $viralrecon_data/genome/kraken2_human --bowtie2_index $viralrecon_data/genome/bowtie2 \
        --nextclade_dataset false --nextclade_dataset_tag false \
        --skip_assembly --max_cpus 8 --max_memory 20.GB \
        -profile docker -resume -bg

ERROR: Validation of pipeline parameters failed!

* --primer_set_version: expected type: Integer, found: Double (4.1)
```

### System information

* Nextflow version = 21.10.4.5656
* Running within a WSL2 install on a Windows 10 computer
* Local executor + desktop hardware
* Docker containers
* Viralrecon version = 2.4

**Comment by drpatelh** [comment]
Thanks for reporting @tetedange13 ! @stevin-wilson has fixed this for us in v2.4.1 which will be released today.
