### ISSUE TITLE
Addition of Freyja tool in viralrecon pipeline

### ISSUE THREAD

**Issue by poojasgupta** [nf-core/viralrecon#299]
### Description of feature

I have been using viralrecon for analyzing wastewater sample data and it works quite well. It just requires some additional post-processing for wastewater data and I was wondering if there is a possibility to add [Freyja](https://github.com/andersen-lab/Freyja) tool as part of viralrecon pipeline. This might be specific to SARS-CoV-2 but could be very helpful for analyzing wastewater data. Freyja estimates relative abundance of various SARS-CoV-2 lineages present in a sample and can discern lineages in a mixed/pooled sample, e.g., in the case of wastewater samples. It needs bam output files after ivar primer trim step and a reference sequence.
Thanks!

**Comment by erinyoung** [comment]
The typical commands for freyja are

```
# calls variants
freyja variants \
      !{bam} \
      --variants freyja/!{sample}_variants.tsv \
      --depths freyja/!{sample}_depths.tsv \
      --ref !{reference_genome} 

# demix
freyja demix \
      freyja/!{sample}_variants.tsv \
      freyja/!{sample}_depths.tsv \
      --output freyja/!{sample}_demix.tsv \
```

Also fairly common are adding bootstraps
```
# boot
freyja boot \
      freyja/!{sample}_variants.tsv \
      freyja/!{sample}_depths.tsv \
      --nt !{task.cpus} \
      --output_base freyja/!{sample}_boot.tsv 
```

And aggregating the data together
```
freyja aggregate <directory with all the demix results>/  --output freyja/aggregated-freyja.tsv
```

**Comment by drpatelh** [comment]
Are you aware of a Nextflow implementation that is already using Freyja @poojasgupta @erinyoung ? Be good to eyeball this to scope out adding to this pipeline.

**Comment by drpatelh** [comment]
@Joon-Klaps has already created a subworkflow and submitted a PR to nf-core/modules https://github.com/nf-core/modules/pull/3003#pullrequestreview-1336575316 🚀 

Will move this to the next milestone in anticipation of adding this at the Hackathon in a couple of weeks.
