### ISSUE TITLE
Add contig field information in vcf header in ivar_variants_to_vcf and use bcftools sort

### ISSUE THREAD

**Issue by saramonzon** [nf-core/viralrecon#306]
### Description of feature

Contig field is recommended in [vcf 4.2 specs](https://samtools.github.io/hts-specs/VCFv4.2.pdf), and it's needed for using bcftools sort in a not indexed vcf. It would be useful for `ivar_variants_to_vcf` to optionally accept a fasta file for including this info in the vcf header.

**Comment by saramonzon** [comment]
Added new mulled container with new dep biopython: https://github.com/BioContainers/multi-package-containers/pull/2140

**Comment by drpatelh** [comment]
Hi @saramonzon! I presume this was fixed in https://github.com/nf-core/viralrecon/pull/308?

**Comment by saramonzon** [comment]
Yes! Exactly!
