### ISSUE TITLE
Conda packages issue with MacOsX

### ISSUE THREAD

**Issue by edgano** [nf-core/viralrecon#31]
Some packages are not available in MacOsX version

_bioconda::sra-tools=2.10.3_ the version available for MacOsX is _bioconda::sra-tools=2.10.1_ 

_wkhtmltopdf=0.12.4_ is not available on MacOsX neither

I dont know if it can be "downgraded" or trigger a WARN/INFO notification asking to use Docker/Singularity

** Conda version:  4.8.2 **

**Comment by drpatelh** [comment]
Not sure there is much we can do about that Im afraid @edgano 😏 Would recommend trying with Docker/Singularity container. Problem with adding a warning is that it may not always be the case where the environment cant build on MacOsX? 

Disclaimer: I have never used a MAC!
