### ISSUE TITLE
Error in the last 2 steps

### ISSUE THREAD

**Issue by ghost** [nf-core/viralrecon#322]
### Description of the bug

Please help. While running the pipeline, there was an error on the second to last step of it

I have since gone into the conda environment in which R was installed and updated it, but all that did was get rid of the first four lines of the message:
```
 Warning message:
  package ‘optparse’ was built under R version 4.0.5 
  Warning message:
  package ‘scales’ was built under R version 4.0.5
```

### Command used and terminal output

```console
nextflow run nf-core/viralrecon --input samplesheet.csv --outdir results/viralrecon --protocol amplicon --genome MN908947.3 --primer_set artic --primer_set_version 3 --platform illumina --skip_assembly --max_cpus 8 --max_memory 13.GB -profile conda

Warning message:
  package ‘optparse’ was built under R version 4.0.5 
  Warning message:
  package ‘scales’ was built under R version 4.0.5 
  Loading required package: grid
  Error: package or namespace load failed for ‘ComplexHeatmap’:
   .onLoad failed in loadNamespace() for 'Cairo', details:
    call: dyn.load(file, DLLpath = DLLpath, ...)
    error: unable to load shared object '/home/yelbur/Desktop/03-consensus/uk_illumina/work/conda/env-05a634cd6ec064941b9d92badb58aa6c/lib/R/library/Cairo/libs/Cairo.so':
    libicuuc.so.70: cannot open shared object file: No such file or directory
  Execution halted
```

### System information

I'm on ubuntu with conda 4.13.0

**Comment by drpatelh** [comment]
Hi @Yelbur ! Did you manage to fix this issue? It looks like your Conda environment is trying to load libraries that may or may not be pre-installed on your system and is failing. Using Conda is susceptible to these sorts of issues and isn't reproducible either. I would recommend using Docker / Singularity if possible. Is this an option for you?

The error appears to be unrelated to the pipeline itself so I will close for now. Please feel free to join the #viralrecon channel on the [nf-core Slack](https://nf-co.re/join) where you can get real-time help from the community.

**Comment by wutron** [comment]
Sorry to reopen a closed issue.  I believe it can be fixed by updating the package version used for conda from `conda-forge::r-base=4.0.3` to `conda-forge::r-base=4.0.5`.
