### ISSUE TITLE
Issues pulling singularity images

### ISSUE THREAD

**Issue by Aqsakhalid30** [nf-core/viralrecon#324]
### Description of the bug

Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:PREPARE_GENOME:BOWTIE2_BUILD (nCoV-2019.reference.fasta)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-bowtie2-2.4.4--py39hbb4e92a_0.img.pulling.1660892881280 https://depot.galaxyproject.org/singularity/bowtie2:2.4.4--py39hbb4e92a_0 > /dev/null
  status : 255
  message:
    [31mFATAL:   While pulling from image from http(s): unexpected EOF

### Command used and terminal output

```console
I have used this command to pull the viralrecon image but i am facing error. 
please suggest
nextflow run nf-core/viralrecon -profile test,singularity --outdir viralrecon
```

### Relevant files

[execution_report_2022-08-19_07-07-25.zip](https://github.com/nf-core/viralrecon/files/9380026/execution_report_2022-08-19_07-07-25.zip)

### System information

ubuntu
container engine: singualrity

**Comment by drpatelh** [comment]
Hi @Aqsakhalid30 ! 

The easiest way to overcome this is to pull the containers before you run the pipeline. You can do this by using the latest version of the nf-core/tools package which you can install via the instructions [here](https://github.com/nf-core/tools#installation).

The command you require would be something like:

```
export NXF_SINGULARITY_CACHEDIR=./singularity_cache
nf-core download --revision 2.5 --compress none --container singularity --singularity-cache-only nf-core/viralrecon
```

All of the containers will be placed in the location specified by `NXF_SINGULARITY_CACHEDIR`. You can change this location to suit your needs. Whenever you launch the pipeline make sure you export that variable beforehand so the pipeline can find the cached containers and you don't have to download them again.

**Comment by Aqsakhalid30** [comment]
dr patelh 
I have tried it on docker as well by using the command below,

nextflow run nf-core/viralrecon -profile test, --outdir viralrecon

i am facing the following issues;



**Execution cancelled -- Finishing pending tasks before exit
-[nf-core/viralrecon] Pipeline completed with errors-
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet_test_illumina_amplicon.csv)'

Caused by:
  Process `NFCORE_VIRALRECON:ILLUMINA:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet_test_illumina_amplicon.csv)` terminated with an error exit status (126)

Command executed:

  check_samplesheet.py \
      samplesheet_test_illumina_amplicon.csv \
      samplesheet.valid.csv \
      --platform illumina
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_VIRALRECON:ILLUMINA:INPUT_CHECK:SAMPLESHEET_CHECK":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=nxf-6ydssnyEDebHQItbdahHBXTA": dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /home/aqsakhalid/work/fe/a8c620cf2e4bd14b10b7df7296c91c

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`**

**Comment by drpatelh** [comment]
Hi @Aqsakhalid30 ! Did you manage to solve this issue? As I mentioned in the comment above the best way to run with Singularity is to pull the images beforehand with `nf-core download`. If you are using Docker, you don't need to do anything as the images will be pulled automatically.

I will close this issue for now but please feel free to join the #viralrecon channel on the [nf-core Slack](https://nf-co.re/join) where you can get real-time help from the community.
