### ISSUE TITLE
Longshot thread 'main' panicked at 'assertion failed: p <= 0.0' error

### ISSUE THREAD

**Issue by ddomman** [nf-core/viralrecon#334]
### Description of the bug

I am hitting this error with longshot intermittently on some of our SARS-CoV-2 nanopore runs using the `medaka` pipeline. 

It has been described here : https://github.com/artic-network/fieldbioinformatics/issues/109

It seems updating to `artic` version 1.2.3 will do the trick.

**Comment by drpatelh** [comment]
artic has been bumped to 1.2.3 in `dev` via https://github.com/nf-core/viralrecon/pull/343
