### ISSUE TITLE
Exit code 255 when running MAKE_VARIANTS_LONG_TABLE process for the test dataset

### ISSUE THREAD

**Issue by mbdabrowska1** [nf-core/viralrecon#339]
### Description of the bug

I'm running the test dataset using singularity profile and everything is running fine until this process:
NFCORE_VIRALRECON:ILLUMINA:VARIANTS_LONG_TABLE:MAKE_VARIANTS_LONG_TABLE
which exits with error code 255 and the following message:
```

[be/ab5e2a] process > NFCORE_VIRALRECON:ILLUMINA:... [100%] 1 of 1, cached: 1 ✔
[0e/23d4b5] process > NFCORE_VIRALRECON:ILLUMINA:... [100%] 3 of 3, cached: 3 ✔
[-        ] process > NFCORE_VIRALRECON:ILLUMINA:... -
[-        ] process > NFCORE_VIRALRECON:ILLUMINA:... -
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/viralrecon] 3/3 samples passed Bowtie2 1000 mapped read threshold:
    37980: SAMPLE2_PE
    48045: SAMPLE1_PE
    46278: SAMPLE3_SE
-
-[nf-core/viralrecon] Pipeline completed with errors-
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:VARIANTS_LONG_TABLE:MAKE_VARIANTS_LONG_TABLE'

Caused by:
  Process `NFCORE_VIRALRECON:ILLUMINA:VARIANTS_LONG_TABLE:MAKE_VARIANTS_LONG_TABLE` terminated with an error exit status (255)

Command executed:

  make_variants_long_table.py \
      --bcftools_query_dir ./bcftools_query \
      --snpsift_dir ./snpsift \
      --pangolin_dir ./pangolin \
      --variant_caller ivar
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_VIRALRECON:ILLUMINA:VARIANTS_LONG_TABLE:MAKE_VARIANTS_LONG_TABLE":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMP as environment variable will not be supported in the future, use APPTAINERENV_TMP instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/13->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/13: kernel reported a bad superblock for squashfs image partition, possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted

Work dir:
  /mnt/fastdata/md1mbdx/HIV_sequencing/viralrecon/work/c5/9fd49b53f801594552b4d0bb9bec3a

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run
```

Is there any known issue with the image for this process? Or perhaps something else is causing this error.

### Command used and terminal output

```console
$ qsub run_viralrecon.sh
```

### Relevant files

#!/bin/sh
#$ -S /bin/sh
#$ -P coguk
#$ -N VR
#$ -l h_rt=2:00:00
#$ -l rmem=8G
#$ -o viralrecon.out
#$ -e viralrecon.err
#$ -M m.b.dabrowska@sheffield.ac.uk
#$ -m a
#$ -V
# Validate job and raise errors

source /etc/profile.d/modules.sh
module load apps/python/conda
module load apps/java

nextflow run nf-core/viralrecon -profile test,singularity \
--outdir results \
-resume \
-with-report \
-with-trace \
-with-timeline \

**Comment by laura-munatx** [comment]
I have found the same issue running the nf-core/rnaseq pipeline on the Mark Dup with Picard (`NFCORE_RNASEQ:RNASEQ:MARK_DUPLICATES_PICARD:PICARD_MARKDUPLICATES`) 

```
Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/9->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/9: squashfuse_ll exited with status 255: Something went wrong trying to read the squashfs image.
```

Did you find any solution?

Thanks !!

**Comment by mbdabrowska1** [comment]
I didn't find any solution sadly!

**Comment by drpatelh** [comment]
Hi @mbdabrowska1 @laura-munatx ! Did you manage to fix this? That error does look like an issue with Singularity / squashfs and is unrelated to this pipeline, especially since it has been observed in rnaseq. Will close this issue but please feel free to join the #viralrecon channel on the [nf-core Slack](https://nf-co.re/join) where you can get real-time help from the community. This particular question may be best suited to #help because it appears to be an infrastructure issue.

**Comment by laura-munatx** [comment]
Hi @drpatelh thanks !  I could not fix it. My conclusion was a mismatch of the version of singularity installed in the HPC I am using and the singularity version used to compile the images that are pulled in the RNA-seq nextflow pipeline. I manually changed the two images that were failing - for a newer / slim version and everything worked perfectly.

**Comment by drpatelh** [comment]
Great! Thanks for the update!
