### ISSUE TITLE
Latest medaka models not available - update artic module

### ISSUE THREAD

**Issue by tavareshugo** [nf-core/viralrecon#341]
### Description of the bug

The latest medaka models cannot be used at the moment, since they are not available through `artic` 1.2.2. 
I have made a [pull request](https://github.com/nf-core/modules/pull/2557) on the core modules to update the version to 1.2.3, if it gets accepted then the pipeline here would need to have its modules updated also.

**Comment by maxulysse** [comment]
I approved and the tests are now running (it was your first PR, so tests were not running).
I'll watch out and comment on your PR if needed

**Comment by maxulysse** [comment]
https://github.com/nf-core/modules/pull/2557 is now merged, do you need help @tavareshugo on making the PR to update the medaka modules?

**Comment by tavareshugo** [comment]
@maxulysse some guidelines would be great, if you don't mind (but I'd like to learn what the workflow is!). Here's what I've done: 

- Forked this repo
- Made a new (for now local) branch to bump artic version
- Ran `nf-core update modules` locally on that branch

But besides updating `modules.json`, this command also moved all these modules: 

`Moved viralrecon/modules/nf-core/modules/bcftools/sort to viralrecon/modules/nf-core/bcftools/sort.`

For basically every `nf-core` module. 

I guess this is not the way to do it?

**Comment by maxulysse** [comment]
I'll have a look first things tomorrow

**Comment by maxulysse** [comment]
ok, so main issue is that we need to merge the TEMPLATE sync (https://github.com/nf-core/viralrecon/pull/331)
Can you pause your this PR for now?
I'll have a look at this #331 PR

**Comment by maxulysse** [comment]
@tavareshugo TEMPLATE has been synced and merged, you can now have a look at updating modules.
with nf-core tools (cf https://nf-co.re/tools/#installation), command should be simply:
```
nf-core modules update artic/guppyplex
nf-core modules update artic/minion
```

**Comment by tavareshugo** [comment]
@maxulysse submitted a pull request -- hope it's all good.

And thanks so much for guiding me in the procedure to make small contributions to these fantastic pipelines!

**Comment by maxulysse** [comment]
I saw, and it looks perfect <3
