### ISSUE TITLE
[DOC] Document full parameters of iVar consensus

### ISSUE THREAD

**Issue by corneliusroemer** [nf-core/viralrecon#348]
I've tried to figure out how exactly you call iVar consensus by default, to understand some issues with artifactual reversions and frameshifts.

However, I could figure out the complete default command that is run.

You have documented one option here: https://nf-co.re/viralrecon/2.5/parameters#min_mapped_reads but I can't see how it flows through the code.

In the module, you allow passing extra args, but I can't find out what they are.

Are they set to anything at all by default? If so what are default args?

The args end up here: https://github.com/nf-core/viralrecon/blob/master/modules/nf-core/modules/ivar/consensus/main.nf#L25

**Comment by saramonzon** [comment]
Hi @corneliusroemer ! 

All default parameters are in `conf/modules_illumina.config` for all processes.

For ivar consensus default parameters are:
https://github.com/nf-core/viralrecon/blob/3ee1fe98fdf17a80922aa8cf4da4afaf483f3429/conf/modules_illumina.config#L556-L562

You can change them using a `custom.config` file and pass it to nextflow using `-c` as follows changing the desired ivar params: 
```
process { 
         withName: 'IVAR_CONSENSUS' { 
             ext.args = '-t 0.75 -q 20 -m 10 -n N' 
        }
}
```

I hope this was what you were asking :)

**Comment by drpatelh** [comment]
Will consider this as answered but we should probably add some more comprehensive docs for this sort of thing to the website. Realised I added docs for updating custom resource requests and containers to the pipeline template but not for tool-specific `ext.args`. 
https://nf-co.re/viralrecon/2.5/usage#custom-configuration

Created a separate issue here:
https://github.com/nf-core/nf-co.re/issues/1643

Ping @jfy133
