### ISSUE TITLE
ERROR in Script plasmidID

### ISSUE THREAD

**Issue by AroobAlhumaidy** [nf-core/viralrecon#349]
### Description of the bug

Hello everyone, 

I'm running Viralrecon for monkeypox, and facing an error: 

## The error: 
```
ERROR in Script plasmidID on or near line 868; exiting with status 1
MESSAGE:  See ./logs/plasmidID.log for more information.
command: gff_to_bed.sh -i ./NO_GROUP/pmseq_V300081052_28_+_V300081052_30/data/pmseq_V300081052_28_+_V300081052_30".gff" -L
```

Is there any solution? 

Thanks, 

### Command used and terminal output

```console

time nextflow run nf-core/viralrecon \
    --input viralrecon.samplesheet.csv  \
    --outdir results  \
    -c custom.config \
    --max_cpus 60 \
    --max_memory '300.GB' \
    --memory-swap '-1' \
    --platform illumina \
    --protocol metagenomic \
    --genome 'NC_063383.1' \
    --nextclade_dataset_name 'hMPXV' \
    -profile docker
```
### Relevant files

[nextflow.log](https://github.com/nf-core/viralrecon/files/10308113/nextflow.log)
[custom.config.txt](https://github.com/nf-core/viralrecon/files/10308164/custom.config.txt)

### System information

- nextflow version 22.10.4.5836
- Container engine: Docker
- Version of nf-core/viralrecon:  2.5

EDIT by @maxulysse: removed extra triple quotes + fix viralrecon version

**Comment by drpatelh** [comment]
`--skip_plasmidid` will be set to true by default which indirectly will fix this issue. Quite a few bugs have propped up that may not be fixed in the short-term. See https://github.com/nf-core/viralrecon/pull/360/commits/5b59dc83cfa4172ebc5b564f4522dd45006ced00
