### ISSUE TITLE
Adding support for Atoplex kit

### ISSUE THREAD

**Issue by ctuni** [nf-core/viralrecon#353]
### Description of feature

Picking up a discussion that arose in the past October Hackathon by @ljmesi regarding adding the [Atoplex](https://en.mgi-tech.com/products/reagents_info/33/) library preparation kit to the list of available primer options.

I have used this kit to process samples and have extensively tested the correct formatting of the bed file available from MGI.

I'm opening the issue to start a conversation here and to confirm the correct way to add the kit would be to modify `genomes.config` file on [configs repo](https://github.com/nf-core/configs/blob/master/conf/pipeline/viralrecon/genomes.config), adding the kit to the bottom of `primer_sets` section.

I could do this change by forking the configs repo and following the basic contribution steps if this is the correct way to add the primer kit. I also understand I would need to fork `viralrecon` branch from `test-datasets` repo to upload the bed file.

Cheers!

**Comment by drpatelh** [comment]
Hi @ctuni ! Yep, you have the flow correct! Update nf-core/test-datasets with the appropriate files and then add the paths to nf-core/configs in that order.

**Comment by ctuni** [comment]
I've created a pull request in the `test-datasets` repo, once reviewed and merged I'll do the second step by doing the change in the `configs` repo :) https://github.com/nf-core/test-datasets/pull/813

**Comment by ctuni** [comment]
Done! See issue on [configs](https://github.com/nf-core/configs/pull/506)
