### ISSUE TITLE
Error "No PSK available. Unable to resume." 

### ISSUE THREAD

**Issue by forty2wallabyway** [nf-core/viralrecon#354]
### Description of the bug

My relevant knowledge is elementary and I don't think this is a viralrecon issue but rather something else that I can't resolve by Googling. My attempt at the pipeline succeeds but is incomplete, with the following error in the .nextflow.log file: 

Feb-14 18:29:29.407 [Actor Thread 23] ERROR nextflow.extension.OperatorImpl - @unknown
javax.net.ssl.SSLException: No PSK available. Unable to resume. 

Any help would be appreciated :)

### Command used and terminal output

```console
nextflow run nf-core/viralrecon \     
  --input samplesheet.csv \     
  --outdir viralrecon_test \     
  --platform illumina \     
  --protocol amplicon \     
  --genome 'MN908947.3' \     
  --primer_set artic \     
  --primer_set_version 3 \  
  -profile singularity


No PSK available. Unable to resume.
 -- Check script '/home/tsherman/.nextflow/assets/nf-core/viralrecon/./workflows/illumina.nf' at line: 130 or see '.nextflow.log' file for more details

No PSK available. Unable to resume.
 -- Check script '/home/tsherman/.nextflow/assets/nf-core/viralrecon/./workflows/illumina.nf' at line: 159 or see '.nextflow.log' file for more details

-[nf-core/viralrecon] Pipeline completed with errors-
```

### Relevant files

[nextflow.log](https://github.com/nf-core/viralrecon/files/10748036/nextflow.log)

### System information

Nextflow version 22.10.6 build 5843
HPC
Singularity
Linux 5.4.0-109-generic

**Comment by drpatelh** [comment]
Hi @forty2wallabyway ! Were you able to solve this issue? I'm afraid I haven't seen this error before but if I had to guess it may be related to Java. It does appear to be unrelated to the pipeline so I will close for now. Please feel free to join the #viralrecon channel on the [nf-core Slack](https://nf-co.re/join) where you can get real-time help from the community.

**Comment by forty2wallabyway** [comment]
Hi there!

It was indeed related to Java - you called it exactly. Thanks for the
response!

Ty
