### ISSUE TITLE
NEB SARS-CoV-2 primers

### ISSUE THREAD

**Issue by tavareshugo** [nf-core/viralrecon#356]
The NEB primer BED files on the config file don't seem to exist: [here ](https://github.com/nf-core/configs/blob/8dfcfa9201c3e48a4374bc79f6687aebf2c0dc3c/conf/pipeline/viralrecon/genomes.config#L75) and [here](https://github.com/nf-core/configs/blob/8dfcfa9201c3e48a4374bc79f6687aebf2c0dc3c/conf/pipeline/viralrecon/genomes.config#L81).

It might also be worth documenting what `vss1` and `vsl1` corresponded to in terms of VarSkip primer versions available from NEB (maybe just a comment in the config would be enough).

**Comment by maxulysse** [comment]
@tavareshugo there is no `NEB` folder in https://github.com/nf-core/test-datasets/tree/viralrecon/genome/MN908947.3/primer_schemes only `artic`, I'm pretty sure that's were the issue lies.

Any idea about that @drpatelh ?

**Comment by drpatelh** [comment]
Oof! The PR adding those files is still open 🤦🏽 
https://github.com/nf-core/test-datasets/pull/299

Don't think anyone checked before merging into nf-core/configs:
https://github.com/nf-core/configs/pull/264#pullrequestreview-723656568

Still need to address my comments on nf-core/test-datasets and then merge for them to become available.

**Comment by drpatelh** [comment]
I have pushed some changes and merged https://github.com/nf-core/test-datasets/pull/299

Fixed the URLs and added a comment in the config regarding the different options for NEB: https://github.com/nf-core/configs/commit/9d05c1b9fbab8211430164312c1ac24437b7bd35

Should be fixed now. Thanks for reporting @tavareshugo !
