### ISSUE TITLE
AWS Access Key Id you provided does not exist in our records

### ISSUE THREAD

**Issue by anca-riza** [nf-core/viralrecon#357]
Hello!

Here running the typical command:
nextflow run nf-core/viralrecon --input samplesheet.csv --platform illumina --protocol amplicon --genome 'MN908947.3' --primer_set artic --primer_set_version 3 --skip_assembly -profile docker
produces:
The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: PJZXQ5FZAWTQH9GM; S3 Extended Request ID: TXcLDOz/N1yKf/fgFGradf2eg9cEo4asEzitppMlel7UsMg7b7fiv7pAnZqGdLRdJa7Kr+VpCVk=)

 -- Check script '/home/genomica/.nextflow/assets/nf-core/viralrecon/./workflows/illumina.nf' at line: 25 or see '.nextflow.log' file for more details 
[nextflow.log](https://github.com/nf-core/configs/files/7765368/nextflow.log) attached

Thank you for looking into this!

**Comment by maxulysse** [comment]
Hi @anca-riza.
I'm sorry we never notice this issue before, I'm afraid it was not open in the correct repo.
I just transferred it to the correct repo, and I'll close it, as I think it doesn't apply anymore.
Please feel free to re-open if it's still an issue for you.
