### ISSUE TITLE
epi2me-labs/wf-cnv failed during analysis

### ISSUE THREAD

**Issue by Ligerd5** [nf-core/viralrecon#389]
Hello, I am new to epi2melabs. I want to analysis CNV in CYP2D6 in chromosome 22. I followed the example on the epi2me/wf-cnv website.

nextflow run epi2me-labs/wf-cnv  --fastq /srv/nabi/EPIMOL_Malaria/FASTQ_CYPD6/fastq_pass/COMBINED/isolate01-COMBINED.fastq.gz  --reference /srv/nabi/EPIMOL_Malaria/copy_number/hg38.fa.gz --bin_size 500

Here is the error message I got and I do not understand how to go about it. Please can I get help on this

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-cnv v0.0.9-g956b861
--------------------------------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : modest_coulomb
  containerEngine: docker
  launchDir      : /srv/nabi/EPIMOL_Malaria/copy_number
  workDir        : /srv/nabi/EPIMOL_Malaria/copy_number/work
  projectDir     : /home/nabi/.nextflow/assets/epi2me-labs/wf-cnv
  userName       : nabi
  profile        : standard
  configFiles    : /home/nabi/.nextflow/assets/epi2me-labs/wf-cnv/nextflow.config

Input Options
  fastq          : /srv/nabi/EPIMOL_Malaria/FASTQ_CYPD6/fastq_pass/COMBINED/isolate01-COMBINED.fastq.gz
  reference      : /srv/nabi/EPIMOL_Malaria/copy_number/hg38.fa.gz

Advanced Options
  map_threads    : 4

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-cnv for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

--------------------------------------------------------------------------------
This is epi2me-labs/wf-cnv v0.0.9-g956b861.
--------------------------------------------------------------------------------
ERROR ~ wf-cnv is now deprecated and will no longer receive updates, please use wf-human-variation

 -- Check '.nextflow.log' file for details
Checking fastq input.
Single file input detected.
executor >  local (3)
[8d/acadf5] process > pipeline:getVersions      [  0%] 0 of 1
[1b/4e5fc0] process > pipeline:getParams        [  0%] 0 of 1
[69/9f749c] process > pipeline:getGenome        [  0%] 0 of 1 ✔
[-        ] process > pipeline:concatenateReads -
[-        ] process > pipeline:alignment        -
[-        ] process > pipeline:samtoolsIndex    -
[-        ] process > pipeline:callCNV          -
[-        ] process > pipeline:makeReport       -
[-        ] process > output                    -
ERROR ~ Error executing process > 'pipeline:getGenome'

Caused by:
  Process `pipeline:getGenome` terminated with an error exit status (127)

Command executed:

  faSize -detailed -tab hg38.fa.gz > hg38.fa.gz_genome.txt
  workflow-glue get_genome --chr_counts hg38.fa.gz_genome.txt -o output.txt
  genome_string=`cat output.txt`

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 290: docker: command not found

Work dir:
  /srv/nabi/EPIMOL_Malaria/copy_number/work/69/9f749c4fb6d59b8cfd7f5256c9cf98

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
ERROR ~ The genome build detected is not compatible with this workflow. Please check the reference sequence and try again.

 -- Check '.nextflow.log' file for details

I honestly do not knw how to troubleshoot this message.
Any help please. Thank you

**Comment by rarthur-eicc** [comment]
This is the viralrecon repo. Did you mean to go [here](https://github.com/epi2me-labs/wf-cnv) ?

**Comment by Ligerd5** [comment]
I followed the example from https://github.com/epi2me-labs/wf-cnv website. I did not use the sample sheet this time. I used it before and still got an error message.

**Comment by Ligerd5** [comment]
I do not understand what this phrase in the error message mean

Caused by:
Process pipeline:getGenome terminated with an error exit status (127)
Command executed:

faSize -detailed -tab hg38.fa.gz > hg38.fa.gz_genome.txt
workflow-glue get_genome --chr_counts hg38.fa.gz_genome.txt -o output.txt
genome_string=cat output.txt

Command exit status:
127

If I understand then I might try to troubleshoot.

**Comment by rarthur-eicc** [comment]
Dude, you’re on the wrong GitHub… wrong software package.

**Comment by Ligerd5** [comment]
Oh. Thank you so much. Will go the right one.

**Comment by maxulysse** [comment]
@Ligerd5 I closed your issue

**Comment by Ligerd5** [comment]
Great. Thank you.
