### ISSUE TITLE
Full-sized dataset

### ISSUE THREAD

**Issue by drpatelh** [nf-core/viralrecon#4]
We will need to obtain a full-sized dataset to test the pipeline from end-to-end. We can just add a `test_full.config` like I have done here for the `atacseq` pipeline:
https://github.com/nf-core/atacseq/blob/dev/conf/test_full.config

This means we can also use the same config for the automated AWS tests that will be carried out before the pipeline is released.

**Comment by saramonzon** [comment]
I'm working on it, this full dataset where should be upload? Because I don't think there will be enough space in the test_repo.

**Comment by heuermh** [comment]
Here is a hacky way to get the list of SRA run IDs from https://www.ncbi.nlm.nih.gov/genbank/sars-cov-2-seqs/

```bash
lynx \
  -dump \
  -nonumbers \
  -listonly \
  https://www.ncbi.nlm.nih.gov/genbank/sars-cov-2-seqs/ |\
  grep 'https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR' |\
  cut -d '=' -f 2
```

**Comment by drpatelh** [comment]
Ideally, it should be available on the web so it can be downloaded at run-time e.g. when running tests locally or on AWS.

Hmmm...this might be a problem if it's something that you have generated in-house. Are there any public datasets available that tick all of the boxes?

**Comment by saramonzon** [comment]
I've gotten the permission to use two in-house samples, we can upload it somewhere, what do you use? Zenodo?

**Comment by drpatelh** [comment]
Um no idea @ewels any ideas where we can upload some in house full-sized datasets to test the pipeline? I don't believe they exist publicly so that isn't an option.

**Comment by ewels** [comment]
Not come across this problem before. I guess Zenodo or Figshare or somewhere like that where we can get a stable persistent URL.

**Comment by saramonzon** [comment]
Ok, I've uploaded two samples to https://zenodo.org/record/3735111

**Comment by drpatelh** [comment]
This looks perfect @saramonzon :100: Maybe we could use Zenodo to upload some other (larger) files that may be required for the pipeline too :thinking:

**Comment by saramonzon** [comment]
Yes! It's really cool!

**Comment by drpatelh** [comment]
We now have a full sized test-dataset for amplicon data on Zenodo. Hoping that we can create a samplesheet to pull the SISPA data on SRA using the proposed implementation from https://github.com/nf-core/viralrecon/issues/6. Do you have the SRA ids and some sample info for this data @saramonzon ?

Will need to edit and add that info into this file:
https://github.com/nf-core/test-datasets/blob/viralrecon/samplesheet_full_sispa.csv

**Comment by drpatelh** [comment]
Done! https://github.com/nf-core/test-datasets/commit/a2282e3da2cad9dae45b378bd11a751f98dd0744
