### ISSUE TITLE
Adding "aggregate" and "plot" methods in the freyja subworkflow

### ISSUE THREAD

**Issue by bsalehe** [nf-core/viralrecon#400]
### Description of feature

Hi,

Thank you for your amazing pipeline. I am currently testing the dev version which contains a wonderful freyja subworkflow for running mixed samples such as wastewater analysis. Please just asking, would it be nicer if you also include the `freyja aggregate` and `freyja plot` methods as they are very useful for downstream analysis? In particular `aggregate` method which tend to aggregate samples for downstream visualisation. 

Cheers!

**Comment by Joon-Klaps** [comment]
Hi, 

With the `aggregate`functionality included would it then be based on existing results? I.e. you give an existing directory of results and then add all your samples to it individually or only combine all the input samples?

**Comment by Joon-Klaps** [comment]
Because if it is the latter, your issue might already be solved when updating the mutliqc version within the pipeline as it supports Freyja but it hasn't been implemented yet in this pipeline.

**Comment by Joon-Klaps** [comment]
#413

**Comment by Joon-Klaps** [comment]
Closing this, feel free to reopen if you think the visualisation with multiqc is not good enough.
