### ISSUE TITLE
Allow skipping `freyja boot`

### ISSUE THREAD

**Issue by tavareshugo** [nf-core/viralrecon#417]
### Description of feature

To save some computation, it may sometimes be desirable to skip `freyja`'s bootstrapping step. 

My suggestion would be to allow using `--freyja_repeats 0`. At the moment, using it like this throws an internal error from freyja. 
But maybe `viralrecon` could interpret 0 (or any negative number, for that matter) as meaning "don't run the bootstrap step".

In fact, it may be worth considering `--freyja_repeats 0` as the default, in case those processing clinical isolates forget to do `--skip_freyja` and end up spending a lot of unnecessary compute time bootstrapping.

I guess an alternative would be to add a new option `--skip_freyja_boot`.

**Comment by Joon-Klaps** [comment]
Good point. 
I'll add a skip_freyja_boot and make sure that repeats are >0
