### ISSUE TITLE
`MOSDEPTH_AMPLICON` doesn't run in `dev` branch

### ISSUE THREAD

**Issue by tavareshugo** [nf-core/viralrecon#419]
### Description of the bug

In the current `dev` branch the modules `MOSDEPTH_AMPLICON` and `PLOT_MOSDEPTH_REGIONS_AMPLICON` seem to be always skipped. 

This may be related to [these changes](https://github.com/nf-core/viralrecon/commit/eb7a82db49ec338079986c1467d1feeaaac7531d). 
I'm sorry, I'm not familiar with the syntax, but maybe @svarona can spot what might be the issue?

The commands I used to test: 

```bash
# current version
nextflow run viralrecon -r 2.6.0 -profile test,singularity --outdir results/v2.6 --skip_assembly --skip_asciigenome --skip_consensus

# development version
nextflow run viralrecon -r dev -profile test,singularity --outdir results/dev --skip_assembly --skip_asciigenome --skip_consensus --skip_freyja
```

(I've skipped several steps to save time for testing)

Both run successfully (i.e. there is no error), but the second one does not run the `MOSDEPTH_AMPLICON` processes.

**Comment by svarona** [comment]
Good spot! Thanks a lot @tavareshugo for this! It seems to be fixed in this PR https://github.com/nf-core/viralrecon/pull/401
