### ISSUE TITLE
fastp version update?

### ISSUE THREAD

**Issue by didiowen** [nf-core/viralrecon#437]
### Description of the bug

Hi everyone,

I'm new to this workflow / pipeline and had just installed the latest version of nextflow. I was trying to run `nextflow run nf-core/viralrecon -profile conda` but I ran into the following error message:

```
WARN: There's no process matching config selector: .*:.*:PREPARE_GENOME:UNTAR_.*
WARN: Task runtime metrics are not reported when using macOS without a container engine
ERROR ~ Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:FASTQ_TRIM_FASTP_FASTQC:FASTP (2)'

Caused by:
  Failed to create Conda environment
    command: conda create --mkdir --yes --quiet --prefix /Users/*****/bioinfo/work/conda/env-5f3a7d0793e009f164e4d72933b51818 bioconda::fastp=0.23.2
    status : 1
    message:
      Channels:
       - conda-forge
       - bioconda
       - defaults
      Platform: osx-arm64
      Collecting package metadata (repodata.json): ...working... done
      Solving environment: ...working... failed
```

I've tried `conda install fastp=0.23.2` it seems that version 0.23.2 is no longer available (at least from my macOS arm64). Is there any way to work around this?

**Comment by Joon-Klaps** [comment]
Hi, yes this can be easily fixed. I'll make a PR for it. 
Within nextflow, you can modify the used environment by specifying a custom configuration file:

```nextflow "my-custom-config.config"
process {
    withName: 'FASTP' {
        conda "bioconda::fastp=0.23.4"
    }
}
``` 
And running it:
`nextflow run nf-core/viralrecon -profile conda,test -c my-custom-config.config --outdir test`. 

That said, viralrecon and all other nf-core pipelines use publicly available tools; not all tools will be compatible with ARM64 (through conda). Instead, running it with docker and specifying the `arm` profile will be easier than searching for ARM-compatible versions and patching all of them. 

`nextflow run nf-core/viralrecon -profile docker,arm,test --outdir test`.
