### ISSUE TITLE
Are GFA outputs from de novo assembly useful?

### ISSUE THREAD

**Issue by heuermh** [nf-core/viralrecon#46]
Created this issue mostly to address this TODO item
[`// TODO nf-core: Rename and output gfa files too?`](https://github.com/nf-core/viralrecon/blob/dev/main.nf#L1381)

**Comment by ekg** [comment]
I think that they can be useful, if you're interested in larger variants. I've done some work on that based on the Shasta assembler output: https://github.com/ekg/shastagfa. We should also be able to apply vg's SV genotyping process to these, by mapping the read set and NC_045512 reference genome to it, then genotyping vs. this reference path.

**Comment by saramonzon** [comment]
I'm not familiar with this kind of outputs! Can you explain some more about which steps we should implement?
I mean we obtain gfas from spades and unicycler, do we need to use shasta? Why is this assembler better or what has it different for the ones we are already using?
Thanks Erick ! I'm learning a lot!

**Comment by heuermh** [comment]
Thank you, @ekg @saramonzon!  Adding GFA from the existing de novo assemblers to workflow results is easy to do.

If we want to pull in the `minia` assembly process, I adapted that to Nextflow here
https://github.com/hpobio-lab/viral-analysis/blob/master/nextflow/assemble.nf

I have also been working on wrapping and Docker-izing the [Cytoscape Assembly app](http://apps.cytoscape.org/apps/assembly) so that it can be used in workflows.  It has flexible visual mappings (e.g. segment sequence length to node width/node color/etc.) and dozens of different layout algorithms and may be a good complement to Bandage and/or odgi visualizations.  It currently renders the structure of the assembly graph (segments & links) rather than the paths through this structure; I would be very welcome to suggestions on how to best visualize these.

**Comment by heuermh** [comment]
Since my last comment I have learned that Docker-izing Cytoscape is not as straightforward as I had hoped, it needs `Xvfb` and might be difficult to call from a shell script as Nextflow does.
