### ISSUE TITLE
apparent 94bp deletion at moderate frequency in "sample1"

### ISSUE THREAD

**Issue by ekg** [nf-core/viralrecon#47]
Referring to the [data posted on zenodo](https://zenodo.org/record/3735111).

I ran this assembly process:

```
cat sample1_R1.fastq.gz sample1_R2.fastq.gz | pigz >sample1.fastq.gz
minia -kmer-size 47 -abundance-min 20 -in sample1.fastq.gz -out sample1.k47.a20
```

Using minimap2 I could see an apparent deletion vs. the reference from this assembly. I made a VCF to describe this by generating a variation graph from the assembly and the reference and using vg deconstruct:

```
cat sample1.k47.a20.contigs.fa ../NC_045512.fa >seqs.fa
minimap2 -w 1 -c -x asm20 ../NC_045512.fa sample1.k47.a20.contigs.fa >seqs.paf
seqwish -s seqs.fa -p seqs.paf -g sample1_vs_ref_k47.a20.gfa
vg convert -x -g sample1_vs_ref_k47.a20.gfa >sample1_vs_ref_k47.a20.xg
vg deconstruct -p NC_045512 sample1_vs_ref_k47.a20.xg
```

Yielding this VCF:

```
##fileformat=VCFv4.2
##contig=<ID=NC_045512,length=29903>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
NC_045512       75      .       CTT     CAAAC   23    . .
NC_045512       241     .       C       T       23    . .
NC_045512       14408   .       C       T       23    . .
NC_045512       11719   .       G       A       23    . .
NC_045512       23403   .       A       G       23    . .
NC_045512       3037    .       C       T       23    . .
NC_045512       23814   .       ATCTTTTGTTGCAATATGGCAGTTTTTGTACACAATTAAACCGTGCTTTAACTGGAATAGCTGTTGAACAAGACAAAAACACCCAAGAAGTTTTTGC       ACA     23      .       .
NC_045512       20268   .       A       G       23    . .
NC_045512       23912   .       C       A       23    . .
NC_045512       23919   .       A       C       23    . .
NC_045512       23916   .       TC      GA      23    . .
```

To investigate, I aligned (with `bwa mem`, default parameters) the read set against this assembly and against the reference NC_045512 sequence. From IGV, I was able to observe that reads match both the reference and deletion allele at this locus.

First, reads against the k47 minia assembly, with the NC_045512 reference at bottom to indicate the precise indel location:

![Screenshot from 2020-04-12 15-32-19](https://user-images.githubusercontent.com/145425/79070629-6efb5780-7cd7-11ea-874b-9440db33c9af.png)

We see some reads mapping across the locus, and some stopping on either side. For some reason, I couldn't find any reads with the same allele as the reference. I think something in the default parameters may be preventing long indels from being detected directly with bwa mem.

Now, inverting things and using NC_045512 as the reference, with the k47 minia assembly at bottom:

![Screenshot from 2020-04-12 15-50-56](https://user-images.githubusercontent.com/145425/79070729-efba5380-7cd7-11ea-912b-6702fb8168b2.png)

Many alignments to the left of the allele show a softclip. Here I'm enabling the display of these sequences:

![Screenshot from 2020-04-12 15-51-46](https://user-images.githubusercontent.com/145425/79070738-05c81400-7cd8-11ea-951c-d05baddb781b.png)

We can see that the sequence matches the other side of the deletion.

In both cases, it's clear that there are reference-matching reads, although at a lower frequency. There seem to be several things happening here, not just the single deletion that's detected. I'm happy to believe that these are all PCR artifacts, until proven otherwise. It's worth noting that a fraction of the reads do directly support at least one of these possible alleles, without error.

What is going on here?

(I don't see this in the other sample, so I don't think it's directly related to the PCR primer set. I'm assuming that was the same.)

**Comment by saramonzon** [comment]
I'm going to try to find this on the other samples we have!  I'm a little puzzle about what can be the issue. It could be a subpopulation, but being in a kind of failing amplicon I don't know, it's weird! 

Thank you very much for the analysis!!

**Comment by drpatelh** [comment]
@saramonzon any updates on this? Are we ok to close?
