### ISSUE TITLE
Efforts to build an MSA of viral genomes

### ISSUE THREAD

**Issue by subwaystation** [nf-core/viralrecon#66]
Hi @viralcon people,
I stumbled upon https://www.biorxiv.org/content/10.1101/2020.04.20.052068v1 and it's code https://github.com/niemasd/ViralMSA. I thought this might be interesting for you. Taking a look at the Python script, it would be ideally suited to port it to a Nextflow pipeline.

**Comment by drpatelh** [comment]
Thanks @subwaystation ! I suspect this is out of the scope of this pipeline at the moment as it is more geared to the individual analysis of viral samples rather than looking at them together using multiple sequence alignment or phylogenetic methods.
