### ISSUE TITLE
Difficulties getting the pipeline run 

### ISSUE THREAD

**Issue by ktrns** [nf-core/viralrecon#67]
Hi guys! 

We will be sequencing several hundred virus strains, and I am looking for a pipeline to do de-novo assembly and variant calling. 

Since I have been working with nfcore @drpatelh in the past, I would like to try out this pipeline. The error message, I am currently getting is: 

```
Error executing process > 'MINIA (L50982_v1_S1_ampfree)'

Caused by:
  Process `MINIA (L50982_v1_S1_ampfree)` terminated with an error exit status (1)

Command executed:

  echo "L50982_v1_S1_ampfree.viral_1.fastq.gz
  L50982_v1_S1_ampfree.viral_2.fastq.gz" > input_files.txt
      minia \
          -kmer-size 31 \
          -abundance-min 20 \
          -nb-cores 6 \
          -in input_files.txt \
          -out L50982_v1_S1_ampfree.k31.a20
      mv L50982_v1_S1_ampfree.k31.a20.contigs.fa L50982_v1_S1_ampfree.k31.scaffolds.fa

Command exit status:
  1
```
and further down in the .command.log: 
```
  EXCEPTION: error opening file: L50982_v1_S1_ampfree.k31.a20.contigs.fa (No such file or directory)
```

The way I run the pipeline, is: 
```
nextflow run nf-core/viralrecon --input $base/samplesheet.S1S2.csv --protocol 'amplicon' --amplicon_bed $ampliconBed --amplicon_fasta $ampliconFasta --genome 'MN908947.3' --igenomes_ignore --kraken2_db $kraken2Db --outdir $base -with-singularity $base/viralrecon_dev.sif -c dcgc.config -r dev
```

Would you be able to help me out? 
Best wishes
Katrin

**Comment by drpatelh** [comment]
Hi @ktrns ! Hope you are and your loved ones are keeping well :)

The `minia` assembler was just added to the pipeline a couple of days ago so we havent really stress tested it much. By default, the pipeline will run [all assembly tools](https://github.com/nf-core/viralrecon/blob/d822d34c427fdfe99e2b3545646e662b4da0e604/nextflow.config#L48) so maybe you can try re-running with `--assemblers spades,metaspades,unicycler -resume`.

Command looks great other than the fact that the pipeline isnt using AWS iGenomes so you can remove the `--igenomes_ignore` flag. 

I would like to know why `minia` is failing though. Can you `cd` into the `work` directory for the process that failed and send me the output of `ls -la` please? May be easier to discuss this in real-time on the #viralrecon channel on nf-core Slack.

**Comment by drpatelh** [comment]
This was partly fixed by using the human Kraken2 database as made available [here](https://zenodo.org/record/3738199). Other issues have been reported on Slack but these relate to not enough viral reads being available to go through some of the assembly steps.
