### ISSUE TITLE
Create full conda environment

### ISSUE THREAD

**Issue by saramonzon** [nf-core/viralrecon#8]
We have two separated environments in the two pipelines we have developed, we need to merge them and check that it works.

**Comment by saramonzon** [comment]
plasmidID is already in conda but we are polishing some issues with dependencies, right now for installing plasmidID:
conda install -c bioconda -c pedroscampoy -c conda-forge plasmidid

**Comment by drpatelh** [comment]
Should be fixed in https://github.com/nf-core/viralrecon/pull/18
